/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountCartAddHybrisWebsitesInner from './AccountCartAddHybrisWebsitesInner';

/**
 * The CartCreate model module.
 * @module model/CartCreate
 * @version 1.1
 */
class CartCreate {
    /**
     * Constructs a new <code>CartCreate</code>.
     * @alias module:model/CartCreate
     * @param cartId {module:model/CartCreate.CartIdEnum} Store’s identifier which you can get from cart_list method
     * @param storeId {String} Store Id
     * @param wixAppId {String} Wix App ID
     * @param wixAppSecretKey {String} Wix App Secret Key
     */
    constructor(cartId, storeId, wixAppId, wixAppSecretKey) { 
        
        CartCreate.initialize(this, cartId, storeId, wixAppId, wixAppSecretKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cartId, storeId, wixAppId, wixAppSecretKey) { 
        obj['cart_id'] = cartId;
        obj['validate_version'] = false;
        obj['verify'] = true;
        obj['ebay_environment'] = 'production';
        obj['ebay_site_id'] = 0;
        obj['store_id'] = storeId;
        obj['environment'] = 'production';
        obj['walmart_environment'] = 'production';
        obj['walmart_region'] = 'us';
        obj['wix_app_id'] = wixAppId;
        obj['wix_app_secret_key'] = wixAppSecretKey;
        obj['allegro_environment'] = 'production';
    }

    /**
     * Constructs a <code>CartCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CartCreate} obj Optional instance to populate.
     * @return {module:model/CartCreate} The populated <code>CartCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartCreate();

            if (data.hasOwnProperty('cart_id')) {
                obj['cart_id'] = ApiClient.convertToType(data['cart_id'], 'String');
            }
            if (data.hasOwnProperty('store_url')) {
                obj['store_url'] = ApiClient.convertToType(data['store_url'], 'String');
            }
            if (data.hasOwnProperty('bridge_url')) {
                obj['bridge_url'] = ApiClient.convertToType(data['bridge_url'], 'String');
            }
            if (data.hasOwnProperty('store_root')) {
                obj['store_root'] = ApiClient.convertToType(data['store_root'], 'String');
            }
            if (data.hasOwnProperty('store_key')) {
                obj['store_key'] = ApiClient.convertToType(data['store_key'], 'String');
            }
            if (data.hasOwnProperty('shared_secret')) {
                obj['shared_secret'] = ApiClient.convertToType(data['shared_secret'], 'String');
            }
            if (data.hasOwnProperty('validate_version')) {
                obj['validate_version'] = ApiClient.convertToType(data['validate_version'], 'Boolean');
            }
            if (data.hasOwnProperty('verify')) {
                obj['verify'] = ApiClient.convertToType(data['verify'], 'Boolean');
            }
            if (data.hasOwnProperty('db_tables_prefix')) {
                obj['db_tables_prefix'] = ApiClient.convertToType(data['db_tables_prefix'], 'String');
            }
            if (data.hasOwnProperty('user_agent')) {
                obj['user_agent'] = ApiClient.convertToType(data['user_agent'], 'String');
            }
            if (data.hasOwnProperty('ftp_host')) {
                obj['ftp_host'] = ApiClient.convertToType(data['ftp_host'], 'String');
            }
            if (data.hasOwnProperty('ftp_user')) {
                obj['ftp_user'] = ApiClient.convertToType(data['ftp_user'], 'String');
            }
            if (data.hasOwnProperty('ftp_password')) {
                obj['ftp_password'] = ApiClient.convertToType(data['ftp_password'], 'String');
            }
            if (data.hasOwnProperty('ftp_port')) {
                obj['ftp_port'] = ApiClient.convertToType(data['ftp_port'], 'Number');
            }
            if (data.hasOwnProperty('ftp_store_dir')) {
                obj['ftp_store_dir'] = ApiClient.convertToType(data['ftp_store_dir'], 'String');
            }
            if (data.hasOwnProperty('apiKey_3dcart')) {
                obj['apiKey_3dcart'] = ApiClient.convertToType(data['apiKey_3dcart'], 'String');
            }
            if (data.hasOwnProperty('AdminAccount')) {
                obj['AdminAccount'] = ApiClient.convertToType(data['AdminAccount'], 'String');
            }
            if (data.hasOwnProperty('ApiPath')) {
                obj['ApiPath'] = ApiClient.convertToType(data['ApiPath'], 'String');
            }
            if (data.hasOwnProperty('ApiKey_Bigcommerce')) {
                obj['ApiKey_Bigcommerce'] = ApiClient.convertToType(data['ApiKey_Bigcommerce'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('accessToken')) {
                obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = ApiClient.convertToType(data['context'], 'String');
            }
            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('apiKey_shopify')) {
                obj['apiKey_shopify'] = ApiClient.convertToType(data['apiKey_shopify'], 'String');
            }
            if (data.hasOwnProperty('apiPassword')) {
                obj['apiPassword'] = ApiClient.convertToType(data['apiPassword'], 'String');
            }
            if (data.hasOwnProperty('accessToken_shopify')) {
                obj['accessToken_shopify'] = ApiClient.convertToType(data['accessToken_shopify'], 'String');
            }
            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
            if (data.hasOwnProperty('apiUsername')) {
                obj['apiUsername'] = ApiClient.convertToType(data['apiUsername'], 'String');
            }
            if (data.hasOwnProperty('EncryptedPassword')) {
                obj['EncryptedPassword'] = ApiClient.convertToType(data['EncryptedPassword'], 'String');
            }
            if (data.hasOwnProperty('Login')) {
                obj['Login'] = ApiClient.convertToType(data['Login'], 'String');
            }
            if (data.hasOwnProperty('apiUser_adnsf')) {
                obj['apiUser_adnsf'] = ApiClient.convertToType(data['apiUser_adnsf'], 'String');
            }
            if (data.hasOwnProperty('apiPass')) {
                obj['apiPass'] = ApiClient.convertToType(data['apiPass'], 'String');
            }
            if (data.hasOwnProperty('privateKey')) {
                obj['privateKey'] = ApiClient.convertToType(data['privateKey'], 'String');
            }
            if (data.hasOwnProperty('appToken')) {
                obj['appToken'] = ApiClient.convertToType(data['appToken'], 'String');
            }
            if (data.hasOwnProperty('etsy_keystring')) {
                obj['etsy_keystring'] = ApiClient.convertToType(data['etsy_keystring'], 'String');
            }
            if (data.hasOwnProperty('etsy_shared_secret')) {
                obj['etsy_shared_secret'] = ApiClient.convertToType(data['etsy_shared_secret'], 'String');
            }
            if (data.hasOwnProperty('tokenSecret')) {
                obj['tokenSecret'] = ApiClient.convertToType(data['tokenSecret'], 'String');
            }
            if (data.hasOwnProperty('etsy_client_id')) {
                obj['etsy_client_id'] = ApiClient.convertToType(data['etsy_client_id'], 'String');
            }
            if (data.hasOwnProperty('etsy_refresh_token')) {
                obj['etsy_refresh_token'] = ApiClient.convertToType(data['etsy_refresh_token'], 'String');
            }
            if (data.hasOwnProperty('ebay_client_id')) {
                obj['ebay_client_id'] = ApiClient.convertToType(data['ebay_client_id'], 'String');
            }
            if (data.hasOwnProperty('ebay_client_secret')) {
                obj['ebay_client_secret'] = ApiClient.convertToType(data['ebay_client_secret'], 'String');
            }
            if (data.hasOwnProperty('ebay_runame')) {
                obj['ebay_runame'] = ApiClient.convertToType(data['ebay_runame'], 'String');
            }
            if (data.hasOwnProperty('ebay_access_token')) {
                obj['ebay_access_token'] = ApiClient.convertToType(data['ebay_access_token'], 'String');
            }
            if (data.hasOwnProperty('ebay_refresh_token')) {
                obj['ebay_refresh_token'] = ApiClient.convertToType(data['ebay_refresh_token'], 'String');
            }
            if (data.hasOwnProperty('ebay_environment')) {
                obj['ebay_environment'] = ApiClient.convertToType(data['ebay_environment'], 'String');
            }
            if (data.hasOwnProperty('ebay_site_id')) {
                obj['ebay_site_id'] = ApiClient.convertToType(data['ebay_site_id'], 'Number');
            }
            if (data.hasOwnProperty('dw_client_id')) {
                obj['dw_client_id'] = ApiClient.convertToType(data['dw_client_id'], 'String');
            }
            if (data.hasOwnProperty('dw_api_pass')) {
                obj['dw_api_pass'] = ApiClient.convertToType(data['dw_api_pass'], 'String');
            }
            if (data.hasOwnProperty('demandware_user_name')) {
                obj['demandware_user_name'] = ApiClient.convertToType(data['demandware_user_name'], 'String');
            }
            if (data.hasOwnProperty('demandware_user_password')) {
                obj['demandware_user_password'] = ApiClient.convertToType(data['demandware_user_password'], 'String');
            }
            if (data.hasOwnProperty('store_id')) {
                obj['store_id'] = ApiClient.convertToType(data['store_id'], 'String');
            }
            if (data.hasOwnProperty('seller_id')) {
                obj['seller_id'] = ApiClient.convertToType(data['seller_id'], 'String');
            }
            if (data.hasOwnProperty('environment')) {
                obj['environment'] = ApiClient.convertToType(data['environment'], 'String');
            }
            if (data.hasOwnProperty('hybris_client_id')) {
                obj['hybris_client_id'] = ApiClient.convertToType(data['hybris_client_id'], 'String');
            }
            if (data.hasOwnProperty('hybris_client_secret')) {
                obj['hybris_client_secret'] = ApiClient.convertToType(data['hybris_client_secret'], 'String');
            }
            if (data.hasOwnProperty('hybris_username')) {
                obj['hybris_username'] = ApiClient.convertToType(data['hybris_username'], 'String');
            }
            if (data.hasOwnProperty('hybris_password')) {
                obj['hybris_password'] = ApiClient.convertToType(data['hybris_password'], 'String');
            }
            if (data.hasOwnProperty('hybris_websites')) {
                obj['hybris_websites'] = ApiClient.convertToType(data['hybris_websites'], [AccountCartAddHybrisWebsitesInner]);
            }
            if (data.hasOwnProperty('walmart_client_id')) {
                obj['walmart_client_id'] = ApiClient.convertToType(data['walmart_client_id'], 'String');
            }
            if (data.hasOwnProperty('walmart_client_secret')) {
                obj['walmart_client_secret'] = ApiClient.convertToType(data['walmart_client_secret'], 'String');
            }
            if (data.hasOwnProperty('walmart_environment')) {
                obj['walmart_environment'] = ApiClient.convertToType(data['walmart_environment'], 'String');
            }
            if (data.hasOwnProperty('walmart_channel_type')) {
                obj['walmart_channel_type'] = ApiClient.convertToType(data['walmart_channel_type'], 'String');
            }
            if (data.hasOwnProperty('walmart_region')) {
                obj['walmart_region'] = ApiClient.convertToType(data['walmart_region'], 'String');
            }
            if (data.hasOwnProperty('lightspeed_api_key')) {
                obj['lightspeed_api_key'] = ApiClient.convertToType(data['lightspeed_api_key'], 'String');
            }
            if (data.hasOwnProperty('lightspeed_api_secret')) {
                obj['lightspeed_api_secret'] = ApiClient.convertToType(data['lightspeed_api_secret'], 'String');
            }
            if (data.hasOwnProperty('shoplazza_access_token')) {
                obj['shoplazza_access_token'] = ApiClient.convertToType(data['shoplazza_access_token'], 'String');
            }
            if (data.hasOwnProperty('shoplazza_shared_secret')) {
                obj['shoplazza_shared_secret'] = ApiClient.convertToType(data['shoplazza_shared_secret'], 'String');
            }
            if (data.hasOwnProperty('shopware_access_key')) {
                obj['shopware_access_key'] = ApiClient.convertToType(data['shopware_access_key'], 'String');
            }
            if (data.hasOwnProperty('shopware_api_key')) {
                obj['shopware_api_key'] = ApiClient.convertToType(data['shopware_api_key'], 'String');
            }
            if (data.hasOwnProperty('shopware_api_secret')) {
                obj['shopware_api_secret'] = ApiClient.convertToType(data['shopware_api_secret'], 'String');
            }
            if (data.hasOwnProperty('commercehq_api_key')) {
                obj['commercehq_api_key'] = ApiClient.convertToType(data['commercehq_api_key'], 'String');
            }
            if (data.hasOwnProperty('commercehq_api_password')) {
                obj['commercehq_api_password'] = ApiClient.convertToType(data['commercehq_api_password'], 'String');
            }
            if (data.hasOwnProperty('3dcart_private_key')) {
                obj['3dcart_private_key'] = ApiClient.convertToType(data['3dcart_private_key'], 'String');
            }
            if (data.hasOwnProperty('3dcart_access_token')) {
                obj['3dcart_access_token'] = ApiClient.convertToType(data['3dcart_access_token'], 'String');
            }
            if (data.hasOwnProperty('wc_consumer_key')) {
                obj['wc_consumer_key'] = ApiClient.convertToType(data['wc_consumer_key'], 'String');
            }
            if (data.hasOwnProperty('wc_consumer_secret')) {
                obj['wc_consumer_secret'] = ApiClient.convertToType(data['wc_consumer_secret'], 'String');
            }
            if (data.hasOwnProperty('magento_consumer_key')) {
                obj['magento_consumer_key'] = ApiClient.convertToType(data['magento_consumer_key'], 'String');
            }
            if (data.hasOwnProperty('magento_consumer_secret')) {
                obj['magento_consumer_secret'] = ApiClient.convertToType(data['magento_consumer_secret'], 'String');
            }
            if (data.hasOwnProperty('magento_access_token')) {
                obj['magento_access_token'] = ApiClient.convertToType(data['magento_access_token'], 'String');
            }
            if (data.hasOwnProperty('magento_token_secret')) {
                obj['magento_token_secret'] = ApiClient.convertToType(data['magento_token_secret'], 'String');
            }
            if (data.hasOwnProperty('prestashop_webservice_key')) {
                obj['prestashop_webservice_key'] = ApiClient.convertToType(data['prestashop_webservice_key'], 'String');
            }
            if (data.hasOwnProperty('wix_app_id')) {
                obj['wix_app_id'] = ApiClient.convertToType(data['wix_app_id'], 'String');
            }
            if (data.hasOwnProperty('wix_app_secret_key')) {
                obj['wix_app_secret_key'] = ApiClient.convertToType(data['wix_app_secret_key'], 'String');
            }
            if (data.hasOwnProperty('wix_instance_id')) {
                obj['wix_instance_id'] = ApiClient.convertToType(data['wix_instance_id'], 'String');
            }
            if (data.hasOwnProperty('wix_refresh_token')) {
                obj['wix_refresh_token'] = ApiClient.convertToType(data['wix_refresh_token'], 'String');
            }
            if (data.hasOwnProperty('mercado_libre_app_id')) {
                obj['mercado_libre_app_id'] = ApiClient.convertToType(data['mercado_libre_app_id'], 'String');
            }
            if (data.hasOwnProperty('mercado_libre_app_secret_key')) {
                obj['mercado_libre_app_secret_key'] = ApiClient.convertToType(data['mercado_libre_app_secret_key'], 'String');
            }
            if (data.hasOwnProperty('mercado_libre_refresh_token')) {
                obj['mercado_libre_refresh_token'] = ApiClient.convertToType(data['mercado_libre_refresh_token'], 'String');
            }
            if (data.hasOwnProperty('zid_client_id')) {
                obj['zid_client_id'] = ApiClient.convertToType(data['zid_client_id'], 'Number');
            }
            if (data.hasOwnProperty('zid_client_secret')) {
                obj['zid_client_secret'] = ApiClient.convertToType(data['zid_client_secret'], 'String');
            }
            if (data.hasOwnProperty('zid_access_token')) {
                obj['zid_access_token'] = ApiClient.convertToType(data['zid_access_token'], 'String');
            }
            if (data.hasOwnProperty('zid_authorization')) {
                obj['zid_authorization'] = ApiClient.convertToType(data['zid_authorization'], 'String');
            }
            if (data.hasOwnProperty('zid_refresh_token')) {
                obj['zid_refresh_token'] = ApiClient.convertToType(data['zid_refresh_token'], 'String');
            }
            if (data.hasOwnProperty('flipkart_client_id')) {
                obj['flipkart_client_id'] = ApiClient.convertToType(data['flipkart_client_id'], 'String');
            }
            if (data.hasOwnProperty('flipkart_client_secret')) {
                obj['flipkart_client_secret'] = ApiClient.convertToType(data['flipkart_client_secret'], 'String');
            }
            if (data.hasOwnProperty('allegro_client_id')) {
                obj['allegro_client_id'] = ApiClient.convertToType(data['allegro_client_id'], 'String');
            }
            if (data.hasOwnProperty('allegro_client_secret')) {
                obj['allegro_client_secret'] = ApiClient.convertToType(data['allegro_client_secret'], 'String');
            }
            if (data.hasOwnProperty('allegro_access_token')) {
                obj['allegro_access_token'] = ApiClient.convertToType(data['allegro_access_token'], 'String');
            }
            if (data.hasOwnProperty('allegro_refresh_token')) {
                obj['allegro_refresh_token'] = ApiClient.convertToType(data['allegro_refresh_token'], 'String');
            }
            if (data.hasOwnProperty('allegro_environment')) {
                obj['allegro_environment'] = ApiClient.convertToType(data['allegro_environment'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CartCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CartCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CartCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['cart_id'] && !(typeof data['cart_id'] === 'string' || data['cart_id'] instanceof String)) {
            throw new Error("Expected the field `cart_id` to be a primitive type in the JSON string but got " + data['cart_id']);
        }
        // ensure the json data is a string
        if (data['store_url'] && !(typeof data['store_url'] === 'string' || data['store_url'] instanceof String)) {
            throw new Error("Expected the field `store_url` to be a primitive type in the JSON string but got " + data['store_url']);
        }
        // ensure the json data is a string
        if (data['bridge_url'] && !(typeof data['bridge_url'] === 'string' || data['bridge_url'] instanceof String)) {
            throw new Error("Expected the field `bridge_url` to be a primitive type in the JSON string but got " + data['bridge_url']);
        }
        // ensure the json data is a string
        if (data['store_root'] && !(typeof data['store_root'] === 'string' || data['store_root'] instanceof String)) {
            throw new Error("Expected the field `store_root` to be a primitive type in the JSON string but got " + data['store_root']);
        }
        // ensure the json data is a string
        if (data['store_key'] && !(typeof data['store_key'] === 'string' || data['store_key'] instanceof String)) {
            throw new Error("Expected the field `store_key` to be a primitive type in the JSON string but got " + data['store_key']);
        }
        // ensure the json data is a string
        if (data['shared_secret'] && !(typeof data['shared_secret'] === 'string' || data['shared_secret'] instanceof String)) {
            throw new Error("Expected the field `shared_secret` to be a primitive type in the JSON string but got " + data['shared_secret']);
        }
        // ensure the json data is a string
        if (data['db_tables_prefix'] && !(typeof data['db_tables_prefix'] === 'string' || data['db_tables_prefix'] instanceof String)) {
            throw new Error("Expected the field `db_tables_prefix` to be a primitive type in the JSON string but got " + data['db_tables_prefix']);
        }
        // ensure the json data is a string
        if (data['user_agent'] && !(typeof data['user_agent'] === 'string' || data['user_agent'] instanceof String)) {
            throw new Error("Expected the field `user_agent` to be a primitive type in the JSON string but got " + data['user_agent']);
        }
        // ensure the json data is a string
        if (data['ftp_host'] && !(typeof data['ftp_host'] === 'string' || data['ftp_host'] instanceof String)) {
            throw new Error("Expected the field `ftp_host` to be a primitive type in the JSON string but got " + data['ftp_host']);
        }
        // ensure the json data is a string
        if (data['ftp_user'] && !(typeof data['ftp_user'] === 'string' || data['ftp_user'] instanceof String)) {
            throw new Error("Expected the field `ftp_user` to be a primitive type in the JSON string but got " + data['ftp_user']);
        }
        // ensure the json data is a string
        if (data['ftp_password'] && !(typeof data['ftp_password'] === 'string' || data['ftp_password'] instanceof String)) {
            throw new Error("Expected the field `ftp_password` to be a primitive type in the JSON string but got " + data['ftp_password']);
        }
        // ensure the json data is a string
        if (data['ftp_store_dir'] && !(typeof data['ftp_store_dir'] === 'string' || data['ftp_store_dir'] instanceof String)) {
            throw new Error("Expected the field `ftp_store_dir` to be a primitive type in the JSON string but got " + data['ftp_store_dir']);
        }
        // ensure the json data is a string
        if (data['apiKey_3dcart'] && !(typeof data['apiKey_3dcart'] === 'string' || data['apiKey_3dcart'] instanceof String)) {
            throw new Error("Expected the field `apiKey_3dcart` to be a primitive type in the JSON string but got " + data['apiKey_3dcart']);
        }
        // ensure the json data is a string
        if (data['AdminAccount'] && !(typeof data['AdminAccount'] === 'string' || data['AdminAccount'] instanceof String)) {
            throw new Error("Expected the field `AdminAccount` to be a primitive type in the JSON string but got " + data['AdminAccount']);
        }
        // ensure the json data is a string
        if (data['ApiPath'] && !(typeof data['ApiPath'] === 'string' || data['ApiPath'] instanceof String)) {
            throw new Error("Expected the field `ApiPath` to be a primitive type in the JSON string but got " + data['ApiPath']);
        }
        // ensure the json data is a string
        if (data['ApiKey_Bigcommerce'] && !(typeof data['ApiKey_Bigcommerce'] === 'string' || data['ApiKey_Bigcommerce'] instanceof String)) {
            throw new Error("Expected the field `ApiKey_Bigcommerce` to be a primitive type in the JSON string but got " + data['ApiKey_Bigcommerce']);
        }
        // ensure the json data is a string
        if (data['client_id'] && !(typeof data['client_id'] === 'string' || data['client_id'] instanceof String)) {
            throw new Error("Expected the field `client_id` to be a primitive type in the JSON string but got " + data['client_id']);
        }
        // ensure the json data is a string
        if (data['accessToken'] && !(typeof data['accessToken'] === 'string' || data['accessToken'] instanceof String)) {
            throw new Error("Expected the field `accessToken` to be a primitive type in the JSON string but got " + data['accessToken']);
        }
        // ensure the json data is a string
        if (data['context'] && !(typeof data['context'] === 'string' || data['context'] instanceof String)) {
            throw new Error("Expected the field `context` to be a primitive type in the JSON string but got " + data['context']);
        }
        // ensure the json data is a string
        if (data['access_token'] && !(typeof data['access_token'] === 'string' || data['access_token'] instanceof String)) {
            throw new Error("Expected the field `access_token` to be a primitive type in the JSON string but got " + data['access_token']);
        }
        // ensure the json data is a string
        if (data['apiKey_shopify'] && !(typeof data['apiKey_shopify'] === 'string' || data['apiKey_shopify'] instanceof String)) {
            throw new Error("Expected the field `apiKey_shopify` to be a primitive type in the JSON string but got " + data['apiKey_shopify']);
        }
        // ensure the json data is a string
        if (data['apiPassword'] && !(typeof data['apiPassword'] === 'string' || data['apiPassword'] instanceof String)) {
            throw new Error("Expected the field `apiPassword` to be a primitive type in the JSON string but got " + data['apiPassword']);
        }
        // ensure the json data is a string
        if (data['accessToken_shopify'] && !(typeof data['accessToken_shopify'] === 'string' || data['accessToken_shopify'] instanceof String)) {
            throw new Error("Expected the field `accessToken_shopify` to be a primitive type in the JSON string but got " + data['accessToken_shopify']);
        }
        // ensure the json data is a string
        if (data['apiKey'] && !(typeof data['apiKey'] === 'string' || data['apiKey'] instanceof String)) {
            throw new Error("Expected the field `apiKey` to be a primitive type in the JSON string but got " + data['apiKey']);
        }
        // ensure the json data is a string
        if (data['apiUsername'] && !(typeof data['apiUsername'] === 'string' || data['apiUsername'] instanceof String)) {
            throw new Error("Expected the field `apiUsername` to be a primitive type in the JSON string but got " + data['apiUsername']);
        }
        // ensure the json data is a string
        if (data['EncryptedPassword'] && !(typeof data['EncryptedPassword'] === 'string' || data['EncryptedPassword'] instanceof String)) {
            throw new Error("Expected the field `EncryptedPassword` to be a primitive type in the JSON string but got " + data['EncryptedPassword']);
        }
        // ensure the json data is a string
        if (data['Login'] && !(typeof data['Login'] === 'string' || data['Login'] instanceof String)) {
            throw new Error("Expected the field `Login` to be a primitive type in the JSON string but got " + data['Login']);
        }
        // ensure the json data is a string
        if (data['apiUser_adnsf'] && !(typeof data['apiUser_adnsf'] === 'string' || data['apiUser_adnsf'] instanceof String)) {
            throw new Error("Expected the field `apiUser_adnsf` to be a primitive type in the JSON string but got " + data['apiUser_adnsf']);
        }
        // ensure the json data is a string
        if (data['apiPass'] && !(typeof data['apiPass'] === 'string' || data['apiPass'] instanceof String)) {
            throw new Error("Expected the field `apiPass` to be a primitive type in the JSON string but got " + data['apiPass']);
        }
        // ensure the json data is a string
        if (data['privateKey'] && !(typeof data['privateKey'] === 'string' || data['privateKey'] instanceof String)) {
            throw new Error("Expected the field `privateKey` to be a primitive type in the JSON string but got " + data['privateKey']);
        }
        // ensure the json data is a string
        if (data['appToken'] && !(typeof data['appToken'] === 'string' || data['appToken'] instanceof String)) {
            throw new Error("Expected the field `appToken` to be a primitive type in the JSON string but got " + data['appToken']);
        }
        // ensure the json data is a string
        if (data['etsy_keystring'] && !(typeof data['etsy_keystring'] === 'string' || data['etsy_keystring'] instanceof String)) {
            throw new Error("Expected the field `etsy_keystring` to be a primitive type in the JSON string but got " + data['etsy_keystring']);
        }
        // ensure the json data is a string
        if (data['etsy_shared_secret'] && !(typeof data['etsy_shared_secret'] === 'string' || data['etsy_shared_secret'] instanceof String)) {
            throw new Error("Expected the field `etsy_shared_secret` to be a primitive type in the JSON string but got " + data['etsy_shared_secret']);
        }
        // ensure the json data is a string
        if (data['tokenSecret'] && !(typeof data['tokenSecret'] === 'string' || data['tokenSecret'] instanceof String)) {
            throw new Error("Expected the field `tokenSecret` to be a primitive type in the JSON string but got " + data['tokenSecret']);
        }
        // ensure the json data is a string
        if (data['etsy_client_id'] && !(typeof data['etsy_client_id'] === 'string' || data['etsy_client_id'] instanceof String)) {
            throw new Error("Expected the field `etsy_client_id` to be a primitive type in the JSON string but got " + data['etsy_client_id']);
        }
        // ensure the json data is a string
        if (data['etsy_refresh_token'] && !(typeof data['etsy_refresh_token'] === 'string' || data['etsy_refresh_token'] instanceof String)) {
            throw new Error("Expected the field `etsy_refresh_token` to be a primitive type in the JSON string but got " + data['etsy_refresh_token']);
        }
        // ensure the json data is a string
        if (data['ebay_client_id'] && !(typeof data['ebay_client_id'] === 'string' || data['ebay_client_id'] instanceof String)) {
            throw new Error("Expected the field `ebay_client_id` to be a primitive type in the JSON string but got " + data['ebay_client_id']);
        }
        // ensure the json data is a string
        if (data['ebay_client_secret'] && !(typeof data['ebay_client_secret'] === 'string' || data['ebay_client_secret'] instanceof String)) {
            throw new Error("Expected the field `ebay_client_secret` to be a primitive type in the JSON string but got " + data['ebay_client_secret']);
        }
        // ensure the json data is a string
        if (data['ebay_runame'] && !(typeof data['ebay_runame'] === 'string' || data['ebay_runame'] instanceof String)) {
            throw new Error("Expected the field `ebay_runame` to be a primitive type in the JSON string but got " + data['ebay_runame']);
        }
        // ensure the json data is a string
        if (data['ebay_access_token'] && !(typeof data['ebay_access_token'] === 'string' || data['ebay_access_token'] instanceof String)) {
            throw new Error("Expected the field `ebay_access_token` to be a primitive type in the JSON string but got " + data['ebay_access_token']);
        }
        // ensure the json data is a string
        if (data['ebay_refresh_token'] && !(typeof data['ebay_refresh_token'] === 'string' || data['ebay_refresh_token'] instanceof String)) {
            throw new Error("Expected the field `ebay_refresh_token` to be a primitive type in the JSON string but got " + data['ebay_refresh_token']);
        }
        // ensure the json data is a string
        if (data['ebay_environment'] && !(typeof data['ebay_environment'] === 'string' || data['ebay_environment'] instanceof String)) {
            throw new Error("Expected the field `ebay_environment` to be a primitive type in the JSON string but got " + data['ebay_environment']);
        }
        // ensure the json data is a string
        if (data['dw_client_id'] && !(typeof data['dw_client_id'] === 'string' || data['dw_client_id'] instanceof String)) {
            throw new Error("Expected the field `dw_client_id` to be a primitive type in the JSON string but got " + data['dw_client_id']);
        }
        // ensure the json data is a string
        if (data['dw_api_pass'] && !(typeof data['dw_api_pass'] === 'string' || data['dw_api_pass'] instanceof String)) {
            throw new Error("Expected the field `dw_api_pass` to be a primitive type in the JSON string but got " + data['dw_api_pass']);
        }
        // ensure the json data is a string
        if (data['demandware_user_name'] && !(typeof data['demandware_user_name'] === 'string' || data['demandware_user_name'] instanceof String)) {
            throw new Error("Expected the field `demandware_user_name` to be a primitive type in the JSON string but got " + data['demandware_user_name']);
        }
        // ensure the json data is a string
        if (data['demandware_user_password'] && !(typeof data['demandware_user_password'] === 'string' || data['demandware_user_password'] instanceof String)) {
            throw new Error("Expected the field `demandware_user_password` to be a primitive type in the JSON string but got " + data['demandware_user_password']);
        }
        // ensure the json data is a string
        if (data['store_id'] && !(typeof data['store_id'] === 'string' || data['store_id'] instanceof String)) {
            throw new Error("Expected the field `store_id` to be a primitive type in the JSON string but got " + data['store_id']);
        }
        // ensure the json data is a string
        if (data['seller_id'] && !(typeof data['seller_id'] === 'string' || data['seller_id'] instanceof String)) {
            throw new Error("Expected the field `seller_id` to be a primitive type in the JSON string but got " + data['seller_id']);
        }
        // ensure the json data is a string
        if (data['environment'] && !(typeof data['environment'] === 'string' || data['environment'] instanceof String)) {
            throw new Error("Expected the field `environment` to be a primitive type in the JSON string but got " + data['environment']);
        }
        // ensure the json data is a string
        if (data['hybris_client_id'] && !(typeof data['hybris_client_id'] === 'string' || data['hybris_client_id'] instanceof String)) {
            throw new Error("Expected the field `hybris_client_id` to be a primitive type in the JSON string but got " + data['hybris_client_id']);
        }
        // ensure the json data is a string
        if (data['hybris_client_secret'] && !(typeof data['hybris_client_secret'] === 'string' || data['hybris_client_secret'] instanceof String)) {
            throw new Error("Expected the field `hybris_client_secret` to be a primitive type in the JSON string but got " + data['hybris_client_secret']);
        }
        // ensure the json data is a string
        if (data['hybris_username'] && !(typeof data['hybris_username'] === 'string' || data['hybris_username'] instanceof String)) {
            throw new Error("Expected the field `hybris_username` to be a primitive type in the JSON string but got " + data['hybris_username']);
        }
        // ensure the json data is a string
        if (data['hybris_password'] && !(typeof data['hybris_password'] === 'string' || data['hybris_password'] instanceof String)) {
            throw new Error("Expected the field `hybris_password` to be a primitive type in the JSON string but got " + data['hybris_password']);
        }
        if (data['hybris_websites']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['hybris_websites'])) {
                throw new Error("Expected the field `hybris_websites` to be an array in the JSON data but got " + data['hybris_websites']);
            }
            // validate the optional field `hybris_websites` (array)
            for (const item of data['hybris_websites']) {
                AccountCartAddHybrisWebsitesInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['walmart_client_id'] && !(typeof data['walmart_client_id'] === 'string' || data['walmart_client_id'] instanceof String)) {
            throw new Error("Expected the field `walmart_client_id` to be a primitive type in the JSON string but got " + data['walmart_client_id']);
        }
        // ensure the json data is a string
        if (data['walmart_client_secret'] && !(typeof data['walmart_client_secret'] === 'string' || data['walmart_client_secret'] instanceof String)) {
            throw new Error("Expected the field `walmart_client_secret` to be a primitive type in the JSON string but got " + data['walmart_client_secret']);
        }
        // ensure the json data is a string
        if (data['walmart_environment'] && !(typeof data['walmart_environment'] === 'string' || data['walmart_environment'] instanceof String)) {
            throw new Error("Expected the field `walmart_environment` to be a primitive type in the JSON string but got " + data['walmart_environment']);
        }
        // ensure the json data is a string
        if (data['walmart_channel_type'] && !(typeof data['walmart_channel_type'] === 'string' || data['walmart_channel_type'] instanceof String)) {
            throw new Error("Expected the field `walmart_channel_type` to be a primitive type in the JSON string but got " + data['walmart_channel_type']);
        }
        // ensure the json data is a string
        if (data['walmart_region'] && !(typeof data['walmart_region'] === 'string' || data['walmart_region'] instanceof String)) {
            throw new Error("Expected the field `walmart_region` to be a primitive type in the JSON string but got " + data['walmart_region']);
        }
        // ensure the json data is a string
        if (data['lightspeed_api_key'] && !(typeof data['lightspeed_api_key'] === 'string' || data['lightspeed_api_key'] instanceof String)) {
            throw new Error("Expected the field `lightspeed_api_key` to be a primitive type in the JSON string but got " + data['lightspeed_api_key']);
        }
        // ensure the json data is a string
        if (data['lightspeed_api_secret'] && !(typeof data['lightspeed_api_secret'] === 'string' || data['lightspeed_api_secret'] instanceof String)) {
            throw new Error("Expected the field `lightspeed_api_secret` to be a primitive type in the JSON string but got " + data['lightspeed_api_secret']);
        }
        // ensure the json data is a string
        if (data['shoplazza_access_token'] && !(typeof data['shoplazza_access_token'] === 'string' || data['shoplazza_access_token'] instanceof String)) {
            throw new Error("Expected the field `shoplazza_access_token` to be a primitive type in the JSON string but got " + data['shoplazza_access_token']);
        }
        // ensure the json data is a string
        if (data['shoplazza_shared_secret'] && !(typeof data['shoplazza_shared_secret'] === 'string' || data['shoplazza_shared_secret'] instanceof String)) {
            throw new Error("Expected the field `shoplazza_shared_secret` to be a primitive type in the JSON string but got " + data['shoplazza_shared_secret']);
        }
        // ensure the json data is a string
        if (data['shopware_access_key'] && !(typeof data['shopware_access_key'] === 'string' || data['shopware_access_key'] instanceof String)) {
            throw new Error("Expected the field `shopware_access_key` to be a primitive type in the JSON string but got " + data['shopware_access_key']);
        }
        // ensure the json data is a string
        if (data['shopware_api_key'] && !(typeof data['shopware_api_key'] === 'string' || data['shopware_api_key'] instanceof String)) {
            throw new Error("Expected the field `shopware_api_key` to be a primitive type in the JSON string but got " + data['shopware_api_key']);
        }
        // ensure the json data is a string
        if (data['shopware_api_secret'] && !(typeof data['shopware_api_secret'] === 'string' || data['shopware_api_secret'] instanceof String)) {
            throw new Error("Expected the field `shopware_api_secret` to be a primitive type in the JSON string but got " + data['shopware_api_secret']);
        }
        // ensure the json data is a string
        if (data['commercehq_api_key'] && !(typeof data['commercehq_api_key'] === 'string' || data['commercehq_api_key'] instanceof String)) {
            throw new Error("Expected the field `commercehq_api_key` to be a primitive type in the JSON string but got " + data['commercehq_api_key']);
        }
        // ensure the json data is a string
        if (data['commercehq_api_password'] && !(typeof data['commercehq_api_password'] === 'string' || data['commercehq_api_password'] instanceof String)) {
            throw new Error("Expected the field `commercehq_api_password` to be a primitive type in the JSON string but got " + data['commercehq_api_password']);
        }
        // ensure the json data is a string
        if (data['3dcart_private_key'] && !(typeof data['3dcart_private_key'] === 'string' || data['3dcart_private_key'] instanceof String)) {
            throw new Error("Expected the field `3dcart_private_key` to be a primitive type in the JSON string but got " + data['3dcart_private_key']);
        }
        // ensure the json data is a string
        if (data['3dcart_access_token'] && !(typeof data['3dcart_access_token'] === 'string' || data['3dcart_access_token'] instanceof String)) {
            throw new Error("Expected the field `3dcart_access_token` to be a primitive type in the JSON string but got " + data['3dcart_access_token']);
        }
        // ensure the json data is a string
        if (data['wc_consumer_key'] && !(typeof data['wc_consumer_key'] === 'string' || data['wc_consumer_key'] instanceof String)) {
            throw new Error("Expected the field `wc_consumer_key` to be a primitive type in the JSON string but got " + data['wc_consumer_key']);
        }
        // ensure the json data is a string
        if (data['wc_consumer_secret'] && !(typeof data['wc_consumer_secret'] === 'string' || data['wc_consumer_secret'] instanceof String)) {
            throw new Error("Expected the field `wc_consumer_secret` to be a primitive type in the JSON string but got " + data['wc_consumer_secret']);
        }
        // ensure the json data is a string
        if (data['magento_consumer_key'] && !(typeof data['magento_consumer_key'] === 'string' || data['magento_consumer_key'] instanceof String)) {
            throw new Error("Expected the field `magento_consumer_key` to be a primitive type in the JSON string but got " + data['magento_consumer_key']);
        }
        // ensure the json data is a string
        if (data['magento_consumer_secret'] && !(typeof data['magento_consumer_secret'] === 'string' || data['magento_consumer_secret'] instanceof String)) {
            throw new Error("Expected the field `magento_consumer_secret` to be a primitive type in the JSON string but got " + data['magento_consumer_secret']);
        }
        // ensure the json data is a string
        if (data['magento_access_token'] && !(typeof data['magento_access_token'] === 'string' || data['magento_access_token'] instanceof String)) {
            throw new Error("Expected the field `magento_access_token` to be a primitive type in the JSON string but got " + data['magento_access_token']);
        }
        // ensure the json data is a string
        if (data['magento_token_secret'] && !(typeof data['magento_token_secret'] === 'string' || data['magento_token_secret'] instanceof String)) {
            throw new Error("Expected the field `magento_token_secret` to be a primitive type in the JSON string but got " + data['magento_token_secret']);
        }
        // ensure the json data is a string
        if (data['prestashop_webservice_key'] && !(typeof data['prestashop_webservice_key'] === 'string' || data['prestashop_webservice_key'] instanceof String)) {
            throw new Error("Expected the field `prestashop_webservice_key` to be a primitive type in the JSON string but got " + data['prestashop_webservice_key']);
        }
        // ensure the json data is a string
        if (data['wix_app_id'] && !(typeof data['wix_app_id'] === 'string' || data['wix_app_id'] instanceof String)) {
            throw new Error("Expected the field `wix_app_id` to be a primitive type in the JSON string but got " + data['wix_app_id']);
        }
        // ensure the json data is a string
        if (data['wix_app_secret_key'] && !(typeof data['wix_app_secret_key'] === 'string' || data['wix_app_secret_key'] instanceof String)) {
            throw new Error("Expected the field `wix_app_secret_key` to be a primitive type in the JSON string but got " + data['wix_app_secret_key']);
        }
        // ensure the json data is a string
        if (data['wix_instance_id'] && !(typeof data['wix_instance_id'] === 'string' || data['wix_instance_id'] instanceof String)) {
            throw new Error("Expected the field `wix_instance_id` to be a primitive type in the JSON string but got " + data['wix_instance_id']);
        }
        // ensure the json data is a string
        if (data['wix_refresh_token'] && !(typeof data['wix_refresh_token'] === 'string' || data['wix_refresh_token'] instanceof String)) {
            throw new Error("Expected the field `wix_refresh_token` to be a primitive type in the JSON string but got " + data['wix_refresh_token']);
        }
        // ensure the json data is a string
        if (data['mercado_libre_app_id'] && !(typeof data['mercado_libre_app_id'] === 'string' || data['mercado_libre_app_id'] instanceof String)) {
            throw new Error("Expected the field `mercado_libre_app_id` to be a primitive type in the JSON string but got " + data['mercado_libre_app_id']);
        }
        // ensure the json data is a string
        if (data['mercado_libre_app_secret_key'] && !(typeof data['mercado_libre_app_secret_key'] === 'string' || data['mercado_libre_app_secret_key'] instanceof String)) {
            throw new Error("Expected the field `mercado_libre_app_secret_key` to be a primitive type in the JSON string but got " + data['mercado_libre_app_secret_key']);
        }
        // ensure the json data is a string
        if (data['mercado_libre_refresh_token'] && !(typeof data['mercado_libre_refresh_token'] === 'string' || data['mercado_libre_refresh_token'] instanceof String)) {
            throw new Error("Expected the field `mercado_libre_refresh_token` to be a primitive type in the JSON string but got " + data['mercado_libre_refresh_token']);
        }
        // ensure the json data is a string
        if (data['zid_client_secret'] && !(typeof data['zid_client_secret'] === 'string' || data['zid_client_secret'] instanceof String)) {
            throw new Error("Expected the field `zid_client_secret` to be a primitive type in the JSON string but got " + data['zid_client_secret']);
        }
        // ensure the json data is a string
        if (data['zid_access_token'] && !(typeof data['zid_access_token'] === 'string' || data['zid_access_token'] instanceof String)) {
            throw new Error("Expected the field `zid_access_token` to be a primitive type in the JSON string but got " + data['zid_access_token']);
        }
        // ensure the json data is a string
        if (data['zid_authorization'] && !(typeof data['zid_authorization'] === 'string' || data['zid_authorization'] instanceof String)) {
            throw new Error("Expected the field `zid_authorization` to be a primitive type in the JSON string but got " + data['zid_authorization']);
        }
        // ensure the json data is a string
        if (data['zid_refresh_token'] && !(typeof data['zid_refresh_token'] === 'string' || data['zid_refresh_token'] instanceof String)) {
            throw new Error("Expected the field `zid_refresh_token` to be a primitive type in the JSON string but got " + data['zid_refresh_token']);
        }
        // ensure the json data is a string
        if (data['flipkart_client_id'] && !(typeof data['flipkart_client_id'] === 'string' || data['flipkart_client_id'] instanceof String)) {
            throw new Error("Expected the field `flipkart_client_id` to be a primitive type in the JSON string but got " + data['flipkart_client_id']);
        }
        // ensure the json data is a string
        if (data['flipkart_client_secret'] && !(typeof data['flipkart_client_secret'] === 'string' || data['flipkart_client_secret'] instanceof String)) {
            throw new Error("Expected the field `flipkart_client_secret` to be a primitive type in the JSON string but got " + data['flipkart_client_secret']);
        }
        // ensure the json data is a string
        if (data['allegro_client_id'] && !(typeof data['allegro_client_id'] === 'string' || data['allegro_client_id'] instanceof String)) {
            throw new Error("Expected the field `allegro_client_id` to be a primitive type in the JSON string but got " + data['allegro_client_id']);
        }
        // ensure the json data is a string
        if (data['allegro_client_secret'] && !(typeof data['allegro_client_secret'] === 'string' || data['allegro_client_secret'] instanceof String)) {
            throw new Error("Expected the field `allegro_client_secret` to be a primitive type in the JSON string but got " + data['allegro_client_secret']);
        }
        // ensure the json data is a string
        if (data['allegro_access_token'] && !(typeof data['allegro_access_token'] === 'string' || data['allegro_access_token'] instanceof String)) {
            throw new Error("Expected the field `allegro_access_token` to be a primitive type in the JSON string but got " + data['allegro_access_token']);
        }
        // ensure the json data is a string
        if (data['allegro_refresh_token'] && !(typeof data['allegro_refresh_token'] === 'string' || data['allegro_refresh_token'] instanceof String)) {
            throw new Error("Expected the field `allegro_refresh_token` to be a primitive type in the JSON string but got " + data['allegro_refresh_token']);
        }
        // ensure the json data is a string
        if (data['allegro_environment'] && !(typeof data['allegro_environment'] === 'string' || data['allegro_environment'] instanceof String)) {
            throw new Error("Expected the field `allegro_environment` to be a primitive type in the JSON string but got " + data['allegro_environment']);
        }

        return true;
    }


}

CartCreate.RequiredProperties = ["cart_id", "store_id", "wix_app_id", "wix_app_secret_key"];

/**
 * Store’s identifier which you can get from cart_list method
 * @member {module:model/CartCreate.CartIdEnum} cart_id
 */
CartCreate.prototype['cart_id'] = undefined;

/**
 * A web address of a store that you would like to connect to API2Cart
 * @member {String} store_url
 */
CartCreate.prototype['store_url'] = undefined;

/**
 * This parameter allows to set up store with custom bridge url (also you must use store_root parameter if a bridge folder is not in the root folder of the store)
 * @member {String} bridge_url
 */
CartCreate.prototype['bridge_url'] = undefined;

/**
 * Absolute path to the store root directory (used with \"bridge_url\" parameter)
 * @member {String} store_root
 */
CartCreate.prototype['store_root'] = undefined;

/**
 * Set this parameter if bridge is already uploaded to store
 * @member {String} store_key
 */
CartCreate.prototype['store_key'] = undefined;

/**
 * Shared secret
 * @member {String} shared_secret
 */
CartCreate.prototype['shared_secret'] = undefined;

/**
 * Specify if api2cart should validate cart version
 * @member {Boolean} validate_version
 * @default false
 */
CartCreate.prototype['validate_version'] = false;

/**
 * Enables or disables cart's verification
 * @member {Boolean} verify
 * @default true
 */
CartCreate.prototype['verify'] = true;

/**
 * DB tables prefix
 * @member {String} db_tables_prefix
 */
CartCreate.prototype['db_tables_prefix'] = undefined;

/**
 * This parameter allows you to set your custom user agent, which will be used in requests to the store. Please use it cautiously, as the store's firewall may block specific values.
 * @member {String} user_agent
 */
CartCreate.prototype['user_agent'] = undefined;

/**
 * FTP connection host
 * @member {String} ftp_host
 */
CartCreate.prototype['ftp_host'] = undefined;

/**
 * FTP User
 * @member {String} ftp_user
 */
CartCreate.prototype['ftp_user'] = undefined;

/**
 * FTP Password
 * @member {String} ftp_password
 */
CartCreate.prototype['ftp_password'] = undefined;

/**
 * FTP Port
 * @member {Number} ftp_port
 */
CartCreate.prototype['ftp_port'] = undefined;

/**
 * FTP Store dir
 * @member {String} ftp_store_dir
 */
CartCreate.prototype['ftp_store_dir'] = undefined;

/**
 * 3DCart API Key
 * @member {String} apiKey_3dcart
 */
CartCreate.prototype['apiKey_3dcart'] = undefined;

/**
 * It's a BigCommerce account for which API is enabled
 * @member {String} AdminAccount
 */
CartCreate.prototype['AdminAccount'] = undefined;

/**
 * BigCommerce API URL
 * @member {String} ApiPath
 */
CartCreate.prototype['ApiPath'] = undefined;

/**
 * Bigcommerce API Key
 * @member {String} ApiKey_Bigcommerce
 */
CartCreate.prototype['ApiKey_Bigcommerce'] = undefined;

/**
 * Client ID of the requesting app
 * @member {String} client_id
 */
CartCreate.prototype['client_id'] = undefined;

/**
 * Access token authorizing the app to access resources on behalf of a user
 * @member {String} accessToken
 */
CartCreate.prototype['accessToken'] = undefined;

/**
 * API Path section unique to the store
 * @member {String} context
 */
CartCreate.prototype['context'] = undefined;

/**
 * Access token authorizing the app to access resources on behalf of a user
 * @member {String} access_token
 */
CartCreate.prototype['access_token'] = undefined;

/**
 * Shopify API Key
 * @member {String} apiKey_shopify
 */
CartCreate.prototype['apiKey_shopify'] = undefined;

/**
 * Shopify API Password
 * @member {String} apiPassword
 */
CartCreate.prototype['apiPassword'] = undefined;

/**
 * Access token authorizing the app to access resources on behalf of a user
 * @member {String} accessToken_shopify
 */
CartCreate.prototype['accessToken_shopify'] = undefined;

/**
 * Neto API Key
 * @member {String} apiKey
 */
CartCreate.prototype['apiKey'] = undefined;

/**
 * Neto User Name
 * @member {String} apiUsername
 */
CartCreate.prototype['apiUsername'] = undefined;

/**
 * Volusion API Password
 * @member {String} EncryptedPassword
 */
CartCreate.prototype['EncryptedPassword'] = undefined;

/**
 * It's a Volusion account for which API is enabled
 * @member {String} Login
 */
CartCreate.prototype['Login'] = undefined;

/**
 * It's a AspDotNetStorefront account for which API is available
 * @member {String} apiUser_adnsf
 */
CartCreate.prototype['apiUser_adnsf'] = undefined;

/**
 * AspDotNetStorefront API Password
 * @member {String} apiPass
 */
CartCreate.prototype['apiPass'] = undefined;

/**
 * 3DCart Application Private Key
 * @member {String} privateKey
 */
CartCreate.prototype['privateKey'] = undefined;

/**
 * 3DCart Token from Application
 * @member {String} appToken
 */
CartCreate.prototype['appToken'] = undefined;

/**
 * Etsy keystring
 * @member {String} etsy_keystring
 */
CartCreate.prototype['etsy_keystring'] = undefined;

/**
 * Etsy shared secret
 * @member {String} etsy_shared_secret
 */
CartCreate.prototype['etsy_shared_secret'] = undefined;

/**
 * Secret token authorizing the app to access resources on behalf of a user
 * @member {String} tokenSecret
 */
CartCreate.prototype['tokenSecret'] = undefined;

/**
 * Etsy Client Id
 * @member {String} etsy_client_id
 */
CartCreate.prototype['etsy_client_id'] = undefined;

/**
 * Etsy Refresh token
 * @member {String} etsy_refresh_token
 */
CartCreate.prototype['etsy_refresh_token'] = undefined;

/**
 * Application ID (AppID).
 * @member {String} ebay_client_id
 */
CartCreate.prototype['ebay_client_id'] = undefined;

/**
 * Shared Secret from eBay application
 * @member {String} ebay_client_secret
 */
CartCreate.prototype['ebay_client_secret'] = undefined;

/**
 * The RuName value that eBay assigns to your application.
 * @member {String} ebay_runame
 */
CartCreate.prototype['ebay_runame'] = undefined;

/**
 * Used to authenticate API requests.
 * @member {String} ebay_access_token
 */
CartCreate.prototype['ebay_access_token'] = undefined;

/**
 * Used to renew the access token.
 * @member {String} ebay_refresh_token
 */
CartCreate.prototype['ebay_refresh_token'] = undefined;

/**
 * eBay environment
 * @member {String} ebay_environment
 * @default 'production'
 */
CartCreate.prototype['ebay_environment'] = 'production';

/**
 * eBay global ID
 * @member {Number} ebay_site_id
 * @default 0
 */
CartCreate.prototype['ebay_site_id'] = 0;

/**
 * Demandware client id
 * @member {String} dw_client_id
 */
CartCreate.prototype['dw_client_id'] = undefined;

/**
 * Demandware api password
 * @member {String} dw_api_pass
 */
CartCreate.prototype['dw_api_pass'] = undefined;

/**
 * Demandware user name
 * @member {String} demandware_user_name
 */
CartCreate.prototype['demandware_user_name'] = undefined;

/**
 * Demandware user password
 * @member {String} demandware_user_password
 */
CartCreate.prototype['demandware_user_password'] = undefined;

/**
 * Store Id
 * @member {String} store_id
 */
CartCreate.prototype['store_id'] = undefined;

/**
 * Seller Id
 * @member {String} seller_id
 */
CartCreate.prototype['seller_id'] = undefined;

/**
 * 
 * @member {String} environment
 * @default 'production'
 */
CartCreate.prototype['environment'] = 'production';

/**
 * Omni Commerce Connector Client ID
 * @member {String} hybris_client_id
 */
CartCreate.prototype['hybris_client_id'] = undefined;

/**
 * Omni Commerce Connector Client Secret
 * @member {String} hybris_client_secret
 */
CartCreate.prototype['hybris_client_secret'] = undefined;

/**
 * User Name
 * @member {String} hybris_username
 */
CartCreate.prototype['hybris_username'] = undefined;

/**
 * User password
 * @member {String} hybris_password
 */
CartCreate.prototype['hybris_password'] = undefined;

/**
 * Websites to stores mapping data
 * @member {Array.<module:model/AccountCartAddHybrisWebsitesInner>} hybris_websites
 */
CartCreate.prototype['hybris_websites'] = undefined;

/**
 * Walmart client ID. For the region 'ca' use Consumer ID
 * @member {String} walmart_client_id
 */
CartCreate.prototype['walmart_client_id'] = undefined;

/**
 * Walmart client secret. For the region 'ca' use Private Key
 * @member {String} walmart_client_secret
 */
CartCreate.prototype['walmart_client_secret'] = undefined;

/**
 * Walmart environment
 * @member {String} walmart_environment
 * @default 'production'
 */
CartCreate.prototype['walmart_environment'] = 'production';

/**
 * Walmart WM_CONSUMER.CHANNEL.TYPE header
 * @member {String} walmart_channel_type
 */
CartCreate.prototype['walmart_channel_type'] = undefined;

/**
 * Walmart region
 * @member {String} walmart_region
 * @default 'us'
 */
CartCreate.prototype['walmart_region'] = 'us';

/**
 * LightSpeed api key
 * @member {String} lightspeed_api_key
 */
CartCreate.prototype['lightspeed_api_key'] = undefined;

/**
 * LightSpeed api secret
 * @member {String} lightspeed_api_secret
 */
CartCreate.prototype['lightspeed_api_secret'] = undefined;

/**
 * Access token authorizing the app to access resources on behalf of a user
 * @member {String} shoplazza_access_token
 */
CartCreate.prototype['shoplazza_access_token'] = undefined;

/**
 * Shared secret
 * @member {String} shoplazza_shared_secret
 */
CartCreate.prototype['shoplazza_shared_secret'] = undefined;

/**
 * Shopware access key
 * @member {String} shopware_access_key
 */
CartCreate.prototype['shopware_access_key'] = undefined;

/**
 * Shopware api key
 * @member {String} shopware_api_key
 */
CartCreate.prototype['shopware_api_key'] = undefined;

/**
 * Shopware client secret access key
 * @member {String} shopware_api_secret
 */
CartCreate.prototype['shopware_api_secret'] = undefined;

/**
 * CommerceHQ api key
 * @member {String} commercehq_api_key
 */
CartCreate.prototype['commercehq_api_key'] = undefined;

/**
 * CommerceHQ api password
 * @member {String} commercehq_api_password
 */
CartCreate.prototype['commercehq_api_password'] = undefined;

/**
 * 3DCart Private Key
 * @member {String} 3dcart_private_key
 */
CartCreate.prototype['3dcart_private_key'] = undefined;

/**
 * 3DCart Token
 * @member {String} 3dcart_access_token
 */
CartCreate.prototype['3dcart_access_token'] = undefined;

/**
 * Woocommerce consumer key
 * @member {String} wc_consumer_key
 */
CartCreate.prototype['wc_consumer_key'] = undefined;

/**
 * Woocommerce consumer secret
 * @member {String} wc_consumer_secret
 */
CartCreate.prototype['wc_consumer_secret'] = undefined;

/**
 * Magento Consumer Key
 * @member {String} magento_consumer_key
 */
CartCreate.prototype['magento_consumer_key'] = undefined;

/**
 * Magento Consumer Secret
 * @member {String} magento_consumer_secret
 */
CartCreate.prototype['magento_consumer_secret'] = undefined;

/**
 * Magento Access Token
 * @member {String} magento_access_token
 */
CartCreate.prototype['magento_access_token'] = undefined;

/**
 * Magento Token Secret
 * @member {String} magento_token_secret
 */
CartCreate.prototype['magento_token_secret'] = undefined;

/**
 * Prestashop webservice key
 * @member {String} prestashop_webservice_key
 */
CartCreate.prototype['prestashop_webservice_key'] = undefined;

/**
 * Wix App ID
 * @member {String} wix_app_id
 */
CartCreate.prototype['wix_app_id'] = undefined;

/**
 * Wix App Secret Key
 * @member {String} wix_app_secret_key
 */
CartCreate.prototype['wix_app_secret_key'] = undefined;

/**
 * Wix Instance ID
 * @member {String} wix_instance_id
 */
CartCreate.prototype['wix_instance_id'] = undefined;

/**
 * Wix refresh token
 * @member {String} wix_refresh_token
 */
CartCreate.prototype['wix_refresh_token'] = undefined;

/**
 * Mercado Libre App ID
 * @member {String} mercado_libre_app_id
 */
CartCreate.prototype['mercado_libre_app_id'] = undefined;

/**
 * Mercado Libre App Secret Key
 * @member {String} mercado_libre_app_secret_key
 */
CartCreate.prototype['mercado_libre_app_secret_key'] = undefined;

/**
 * Mercado Libre Refresh Token
 * @member {String} mercado_libre_refresh_token
 */
CartCreate.prototype['mercado_libre_refresh_token'] = undefined;

/**
 * Zid Client ID
 * @member {Number} zid_client_id
 */
CartCreate.prototype['zid_client_id'] = undefined;

/**
 * Zid Client Secret
 * @member {String} zid_client_secret
 */
CartCreate.prototype['zid_client_secret'] = undefined;

/**
 * Zid Access Token
 * @member {String} zid_access_token
 */
CartCreate.prototype['zid_access_token'] = undefined;

/**
 * Zid Authorization
 * @member {String} zid_authorization
 */
CartCreate.prototype['zid_authorization'] = undefined;

/**
 * Zid refresh token
 * @member {String} zid_refresh_token
 */
CartCreate.prototype['zid_refresh_token'] = undefined;

/**
 * Flipkart Client ID
 * @member {String} flipkart_client_id
 */
CartCreate.prototype['flipkart_client_id'] = undefined;

/**
 * Flipkart Client Secret
 * @member {String} flipkart_client_secret
 */
CartCreate.prototype['flipkart_client_secret'] = undefined;

/**
 * Allegro Client ID
 * @member {String} allegro_client_id
 */
CartCreate.prototype['allegro_client_id'] = undefined;

/**
 * Allegro Client Secret
 * @member {String} allegro_client_secret
 */
CartCreate.prototype['allegro_client_secret'] = undefined;

/**
 * Allegro Access Token
 * @member {String} allegro_access_token
 */
CartCreate.prototype['allegro_access_token'] = undefined;

/**
 * Allegro Refresh Token
 * @member {String} allegro_refresh_token
 */
CartCreate.prototype['allegro_refresh_token'] = undefined;

/**
 * Allegro Environment
 * @member {String} allegro_environment
 * @default 'production'
 */
CartCreate.prototype['allegro_environment'] = 'production';





/**
 * Allowed values for the <code>cart_id</code> property.
 * @enum {String}
 * @readonly
 */
CartCreate['CartIdEnum'] = {

    /**
     * value: "3DCart"
     * @const
     */
    "3DCart": "3DCart",

    /**
     * value: "3DCartApi"
     * @const
     */
    "3DCartApi": "3DCartApi",

    /**
     * value: "AceShop"
     * @const
     */
    "AceShop": "AceShop",

    /**
     * value: "AmazonSP"
     * @const
     */
    "AmazonSP": "AmazonSP",

    /**
     * value: "AspDotNetStorefront"
     * @const
     */
    "AspDotNetStorefront": "AspDotNetStorefront",

    /**
     * value: "BigCartel"
     * @const
     */
    "BigCartel": "BigCartel",

    /**
     * value: "BigcommerceApi"
     * @const
     */
    "BigcommerceApi": "BigcommerceApi",

    /**
     * value: "Bol"
     * @const
     */
    "Bol": "Bol",

    /**
     * value: "CommerceHQ"
     * @const
     */
    "CommerceHQ": "CommerceHQ",

    /**
     * value: "Creloaded"
     * @const
     */
    "Creloaded": "Creloaded",

    /**
     * value: "Cscart"
     * @const
     */
    "Cscart": "Cscart",

    /**
     * value: "Cubecart"
     * @const
     */
    "Cubecart": "Cubecart",

    /**
     * value: "Demandware"
     * @const
     */
    "Demandware": "Demandware",

    /**
     * value: "EBay"
     * @const
     */
    "EBay": "EBay",

    /**
     * value: "Ecwid"
     * @const
     */
    "Ecwid": "Ecwid",

    /**
     * value: "EtsyAPIv3"
     * @const
     */
    "EtsyAPIv3": "EtsyAPIv3",

    /**
     * value: "Flipkart"
     * @const
     */
    "Flipkart": "Flipkart",

    /**
     * value: "Gambio"
     * @const
     */
    "Gambio": "Gambio",

    /**
     * value: "Hybris"
     * @const
     */
    "Hybris": "Hybris",

    /**
     * value: "JooCart"
     * @const
     */
    "JooCart": "JooCart",

    /**
     * value: "Lazada"
     * @const
     */
    "Lazada": "Lazada",

    /**
     * value: "LightSpeed"
     * @const
     */
    "LightSpeed": "LightSpeed",

    /**
     * value: "Magento1212"
     * @const
     */
    "Magento1212": "Magento1212",

    /**
     * value: "Magento2Api"
     * @const
     */
    "Magento2Api": "Magento2Api",

    /**
     * value: "MercadoLibre"
     * @const
     */
    "MercadoLibre": "MercadoLibre",

    /**
     * value: "MijoShop"
     * @const
     */
    "MijoShop": "MijoShop",

    /**
     * value: "Miva"
     * @const
     */
    "Miva": "Miva",

    /**
     * value: "Neto"
     * @const
     */
    "Neto": "Neto",

    /**
     * value: "Opencart14"
     * @const
     */
    "Opencart14": "Opencart14",

    /**
     * value: "Oscmax2"
     * @const
     */
    "Oscmax2": "Oscmax2",

    /**
     * value: "Oscommerce22ms2"
     * @const
     */
    "Oscommerce22ms2": "Oscommerce22ms2",

    /**
     * value: "Otto"
     * @const
     */
    "Otto": "Otto",

    /**
     * value: "Oxid"
     * @const
     */
    "Oxid": "Oxid",

    /**
     * value: "Pinnacle"
     * @const
     */
    "Pinnacle": "Pinnacle",

    /**
     * value: "Prestashop"
     * @const
     */
    "Prestashop": "Prestashop",

    /**
     * value: "PrestashopApi"
     * @const
     */
    "PrestashopApi": "PrestashopApi",

    /**
     * value: "SSPremium"
     * @const
     */
    "SSPremium": "SSPremium",

    /**
     * value: "Salla"
     * @const
     */
    "Salla": "Salla",

    /**
     * value: "Shopify"
     * @const
     */
    "Shopify": "Shopify",

    /**
     * value: "Shopee"
     * @const
     */
    "Shopee": "Shopee",

    /**
     * value: "Shoplazza"
     * @const
     */
    "Shoplazza": "Shoplazza",

    /**
     * value: "Shopline"
     * @const
     */
    "Shopline": "Shopline",

    /**
     * value: "Shopware"
     * @const
     */
    "Shopware": "Shopware",

    /**
     * value: "ShopwareApi"
     * @const
     */
    "ShopwareApi": "ShopwareApi",

    /**
     * value: "Square"
     * @const
     */
    "Square": "Square",

    /**
     * value: "Squarespace"
     * @const
     */
    "Squarespace": "Squarespace",

    /**
     * value: "Temu"
     * @const
     */
    "Temu": "Temu",

    /**
     * value: "Tiendanube"
     * @const
     */
    "Tiendanube": "Tiendanube",

    /**
     * value: "TikTokShop"
     * @const
     */
    "TikTokShop": "TikTokShop",

    /**
     * value: "Tomatocart"
     * @const
     */
    "Tomatocart": "Tomatocart",

    /**
     * value: "Ubercart"
     * @const
     */
    "Ubercart": "Ubercart",

    /**
     * value: "Virtuemart"
     * @const
     */
    "Virtuemart": "Virtuemart",

    /**
     * value: "Volusion"
     * @const
     */
    "Volusion": "Volusion",

    /**
     * value: "WPecommerce"
     * @const
     */
    "WPecommerce": "WPecommerce",

    /**
     * value: "Walmart"
     * @const
     */
    "Walmart": "Walmart",

    /**
     * value: "WebAsyst"
     * @const
     */
    "WebAsyst": "WebAsyst",

    /**
     * value: "Wix"
     * @const
     */
    "Wix": "Wix",

    /**
     * value: "Woocommerce"
     * @const
     */
    "Woocommerce": "Woocommerce",

    /**
     * value: "WoocommerceApi"
     * @const
     */
    "WoocommerceApi": "WoocommerceApi",

    /**
     * value: "Xcart"
     * @const
     */
    "Xcart": "Xcart",

    /**
     * value: "Xtcommerce"
     * @const
     */
    "Xtcommerce": "Xtcommerce",

    /**
     * value: "XtcommerceVeyton"
     * @const
     */
    "XtcommerceVeyton": "XtcommerceVeyton",

    /**
     * value: "Zencart137"
     * @const
     */
    "Zencart137": "Zencart137",

    /**
     * value: "Zid"
     * @const
     */
    "Zid": "Zid",

    /**
     * value: "Zoey"
     * @const
     */
    "Zoey": "Zoey",

    /**
     * value: "Zoho"
     * @const
     */
    "Zoho": "Zoho"
};



export default CartCreate;

