/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomerAddConsentsInner from './CustomerAddConsentsInner';
import CustomerUpdateAddressInner from './CustomerUpdateAddressInner';

/**
 * The CustomerUpdate model module.
 * @module model/CustomerUpdate
 * @version 1.1
 */
class CustomerUpdate {
    /**
     * Constructs a new <code>CustomerUpdate</code>.
     * @alias module:model/CustomerUpdate
     */
    constructor() { 
        
        CustomerUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerUpdate} obj Optional instance to populate.
     * @return {module:model/CustomerUpdate} The populated <code>CustomerUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerUpdate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'String');
            }
            if (data.hasOwnProperty('group_ids')) {
                obj['group_ids'] = ApiClient.convertToType(data['group_ids'], 'String');
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('birth_day')) {
                obj['birth_day'] = ApiClient.convertToType(data['birth_day'], 'String');
            }
            if (data.hasOwnProperty('news_letter_subscription')) {
                obj['news_letter_subscription'] = ApiClient.convertToType(data['news_letter_subscription'], 'Boolean');
            }
            if (data.hasOwnProperty('consents')) {
                obj['consents'] = ApiClient.convertToType(data['consents'], [CustomerAddConsentsInner]);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('store_id')) {
                obj['store_id'] = ApiClient.convertToType(data['store_id'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], [CustomerUpdateAddressInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['group_id'] && !(typeof data['group_id'] === 'string' || data['group_id'] instanceof String)) {
            throw new Error("Expected the field `group_id` to be a primitive type in the JSON string but got " + data['group_id']);
        }
        // ensure the json data is a string
        if (data['group_ids'] && !(typeof data['group_ids'] === 'string' || data['group_ids'] instanceof String)) {
            throw new Error("Expected the field `group_ids` to be a primitive type in the JSON string but got " + data['group_ids']);
        }
        // ensure the json data is a string
        if (data['group'] && !(typeof data['group'] === 'string' || data['group'] instanceof String)) {
            throw new Error("Expected the field `group` to be a primitive type in the JSON string but got " + data['group']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['birth_day'] && !(typeof data['birth_day'] === 'string' || data['birth_day'] instanceof String)) {
            throw new Error("Expected the field `birth_day` to be a primitive type in the JSON string but got " + data['birth_day']);
        }
        if (data['consents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['consents'])) {
                throw new Error("Expected the field `consents` to be an array in the JSON data but got " + data['consents']);
            }
            // validate the optional field `consents` (array)
            for (const item of data['consents']) {
                CustomerAddConsentsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['tags'] && !(typeof data['tags'] === 'string' || data['tags'] instanceof String)) {
            throw new Error("Expected the field `tags` to be a primitive type in the JSON string but got " + data['tags']);
        }
        // ensure the json data is a string
        if (data['gender'] && !(typeof data['gender'] === 'string' || data['gender'] instanceof String)) {
            throw new Error("Expected the field `gender` to be a primitive type in the JSON string but got " + data['gender']);
        }
        // ensure the json data is a string
        if (data['note'] && !(typeof data['note'] === 'string' || data['note'] instanceof String)) {
            throw new Error("Expected the field `note` to be a primitive type in the JSON string but got " + data['note']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['store_id'] && !(typeof data['store_id'] === 'string' || data['store_id'] instanceof String)) {
            throw new Error("Expected the field `store_id` to be a primitive type in the JSON string but got " + data['store_id']);
        }
        if (data['address']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['address'])) {
                throw new Error("Expected the field `address` to be an array in the JSON data but got " + data['address']);
            }
            // validate the optional field `address` (array)
            for (const item of data['address']) {
                CustomerUpdateAddressInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Entity id
 * @member {String} id
 */
CustomerUpdate.prototype['id'] = undefined;

/**
 * Customer group_id
 * @member {String} group_id
 */
CustomerUpdate.prototype['group_id'] = undefined;

/**
 * Groups that will be assigned to a customer
 * @member {String} group_ids
 */
CustomerUpdate.prototype['group_ids'] = undefined;

/**
 * Defines the group where the customer
 * @member {String} group
 */
CustomerUpdate.prototype['group'] = undefined;

/**
 * Defines customer's email
 * @member {String} email
 */
CustomerUpdate.prototype['email'] = undefined;

/**
 * Defines customer's phone number
 * @member {String} phone
 */
CustomerUpdate.prototype['phone'] = undefined;

/**
 * Defines customer's first name
 * @member {String} first_name
 */
CustomerUpdate.prototype['first_name'] = undefined;

/**
 * Defines customer's last name
 * @member {String} last_name
 */
CustomerUpdate.prototype['last_name'] = undefined;

/**
 * Defines customer's birthday
 * @member {String} birth_day
 */
CustomerUpdate.prototype['birth_day'] = undefined;

/**
 * Defines whether the newsletter subscription is available for the user
 * @member {Boolean} news_letter_subscription
 */
CustomerUpdate.prototype['news_letter_subscription'] = undefined;

/**
 * Defines consents to notifications
 * @member {Array.<module:model/CustomerAddConsentsInner>} consents
 */
CustomerUpdate.prototype['consents'] = undefined;

/**
 * Customer tags
 * @member {String} tags
 */
CustomerUpdate.prototype['tags'] = undefined;

/**
 * Defines customer's gender
 * @member {String} gender
 */
CustomerUpdate.prototype['gender'] = undefined;

/**
 * The customer note.
 * @member {String} note
 */
CustomerUpdate.prototype['note'] = undefined;

/**
 * Defines customer's status
 * @member {String} status
 */
CustomerUpdate.prototype['status'] = undefined;

/**
 * Store Id
 * @member {String} store_id
 */
CustomerUpdate.prototype['store_id'] = undefined;

/**
 * @member {Array.<module:model/CustomerUpdateAddressInner>} address
 */
CustomerUpdate.prototype['address'] = undefined;






export default CustomerUpdate;

