/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductAddSpecificsInnerGroupProductsDetailsInner model module.
 * @module model/ProductAddSpecificsInnerGroupProductsDetailsInner
 * @version 1.1
 */
class ProductAddSpecificsInnerGroupProductsDetailsInner {
    /**
     * Constructs a new <code>ProductAddSpecificsInnerGroupProductsDetailsInner</code>.
     * @alias module:model/ProductAddSpecificsInnerGroupProductsDetailsInner
     * @param id {String} 
     * @param quantity {Number} 
     */
    constructor(id, quantity) { 
        
        ProductAddSpecificsInnerGroupProductsDetailsInner.initialize(this, id, quantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, quantity) { 
        obj['id'] = id;
        obj['quantity'] = quantity;
    }

    /**
     * Constructs a <code>ProductAddSpecificsInnerGroupProductsDetailsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductAddSpecificsInnerGroupProductsDetailsInner} obj Optional instance to populate.
     * @return {module:model/ProductAddSpecificsInnerGroupProductsDetailsInner} The populated <code>ProductAddSpecificsInnerGroupProductsDetailsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductAddSpecificsInnerGroupProductsDetailsInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductAddSpecificsInnerGroupProductsDetailsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductAddSpecificsInnerGroupProductsDetailsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductAddSpecificsInnerGroupProductsDetailsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

ProductAddSpecificsInnerGroupProductsDetailsInner.RequiredProperties = ["id", "quantity"];

/**
 * @member {String} id
 */
ProductAddSpecificsInnerGroupProductsDetailsInner.prototype['id'] = undefined;

/**
 * @member {Number} quantity
 */
ProductAddSpecificsInnerGroupProductsDetailsInner.prototype['quantity'] = undefined;






export default ProductAddSpecificsInnerGroupProductsDetailsInner;

