/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductAddBatchPayloadInnerImagesInner from './ProductAddBatchPayloadInnerImagesInner';
import ProductUpdateBatchPayloadInnerAdvancedPricesInner from './ProductUpdateBatchPayloadInnerAdvancedPricesInner';
import ProductVariantAddBatchPayloadInnerCombinationInner from './ProductVariantAddBatchPayloadInnerCombinationInner';

/**
 * The ProductVariantAddBatchPayloadInner model module.
 * @module model/ProductVariantAddBatchPayloadInner
 * @version 1.1
 */
class ProductVariantAddBatchPayloadInner {
    /**
     * Constructs a new <code>ProductVariantAddBatchPayloadInner</code>.
     * @alias module:model/ProductVariantAddBatchPayloadInner
     * @param productId {String} 
     * @param combination {Array.<module:model/ProductVariantAddBatchPayloadInnerCombinationInner>} A unique combination that contains an array of options and their values, which form a variation.
     * @param sku {String} 
     */
    constructor(productId, combination, sku) { 
        
        ProductVariantAddBatchPayloadInner.initialize(this, productId, combination, sku);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productId, combination, sku) { 
        obj['product_id'] = productId;
        obj['combination'] = combination;
        obj['sku'] = sku;
    }

    /**
     * Constructs a <code>ProductVariantAddBatchPayloadInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductVariantAddBatchPayloadInner} obj Optional instance to populate.
     * @return {module:model/ProductVariantAddBatchPayloadInner} The populated <code>ProductVariantAddBatchPayloadInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductVariantAddBatchPayloadInner();

            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
            }
            if (data.hasOwnProperty('combination')) {
                obj['combination'] = ApiClient.convertToType(data['combination'], [ProductVariantAddBatchPayloadInnerCombinationInner]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('short_description')) {
                obj['short_description'] = ApiClient.convertToType(data['short_description'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('old_price')) {
                obj['old_price'] = ApiClient.convertToType(data['old_price'], 'Number');
            }
            if (data.hasOwnProperty('cost_price')) {
                obj['cost_price'] = ApiClient.convertToType(data['cost_price'], 'Number');
            }
            if (data.hasOwnProperty('special_price')) {
                obj['special_price'] = ApiClient.convertToType(data['special_price'], 'Number');
            }
            if (data.hasOwnProperty('sprice_create')) {
                obj['sprice_create'] = ApiClient.convertToType(data['sprice_create'], 'String');
            }
            if (data.hasOwnProperty('sprice_expire')) {
                obj['sprice_expire'] = ApiClient.convertToType(data['sprice_expire'], 'String');
            }
            if (data.hasOwnProperty('advanced_prices')) {
                obj['advanced_prices'] = ApiClient.convertToType(data['advanced_prices'], [ProductUpdateBatchPayloadInnerAdvancedPricesInner]);
            }
            if (data.hasOwnProperty('meta_title')) {
                obj['meta_title'] = ApiClient.convertToType(data['meta_title'], 'Number');
            }
            if (data.hasOwnProperty('meta_description')) {
                obj['meta_description'] = ApiClient.convertToType(data['meta_description'], 'Number');
            }
            if (data.hasOwnProperty('meta_keywords')) {
                obj['meta_keywords'] = ApiClient.convertToType(data['meta_keywords'], ['String']);
            }
            if (data.hasOwnProperty('categories_ids')) {
                obj['categories_ids'] = ApiClient.convertToType(data['categories_ids'], ['String']);
            }
            if (data.hasOwnProperty('stores_ids')) {
                obj['stores_ids'] = ApiClient.convertToType(data['stores_ids'], ['String']);
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
            if (data.hasOwnProperty('weight_unit')) {
                obj['weight_unit'] = ApiClient.convertToType(data['weight_unit'], 'String');
            }
            if (data.hasOwnProperty('warehouse_id')) {
                obj['warehouse_id'] = ApiClient.convertToType(data['warehouse_id'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('manage_stock')) {
                obj['manage_stock'] = ApiClient.convertToType(data['manage_stock'], 'Boolean');
            }
            if (data.hasOwnProperty('in_stock')) {
                obj['in_stock'] = ApiClient.convertToType(data['in_stock'], 'Boolean');
            }
            if (data.hasOwnProperty('store_id')) {
                obj['store_id'] = ApiClient.convertToType(data['store_id'], 'String');
            }
            if (data.hasOwnProperty('lang_id')) {
                obj['lang_id'] = ApiClient.convertToType(data['lang_id'], 'String');
            }
            if (data.hasOwnProperty('tax_class_id')) {
                obj['tax_class_id'] = ApiClient.convertToType(data['tax_class_id'], 'String');
            }
            if (data.hasOwnProperty('backorder_status')) {
                obj['backorder_status'] = ApiClient.convertToType(data['backorder_status'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'String');
            }
            if (data.hasOwnProperty('is_virtual')) {
                obj['is_virtual'] = ApiClient.convertToType(data['is_virtual'], 'Boolean');
            }
            if (data.hasOwnProperty('downloadable')) {
                obj['downloadable'] = ApiClient.convertToType(data['downloadable'], 'Boolean');
            }
            if (data.hasOwnProperty('is_default')) {
                obj['is_default'] = ApiClient.convertToType(data['is_default'], 'Boolean');
            }
            if (data.hasOwnProperty('upc')) {
                obj['upc'] = ApiClient.convertToType(data['upc'], 'String');
            }
            if (data.hasOwnProperty('isbn')) {
                obj['isbn'] = ApiClient.convertToType(data['isbn'], 'String');
            }
            if (data.hasOwnProperty('mpn')) {
                obj['mpn'] = ApiClient.convertToType(data['mpn'], 'String');
            }
            if (data.hasOwnProperty('ean')) {
                obj['ean'] = ApiClient.convertToType(data['ean'], 'String');
            }
            if (data.hasOwnProperty('barcode')) {
                obj['barcode'] = ApiClient.convertToType(data['barcode'], 'String');
            }
            if (data.hasOwnProperty('available_for_sale')) {
                obj['available_for_sale'] = ApiClient.convertToType(data['available_for_sale'], 'Boolean');
            }
            if (data.hasOwnProperty('is_free_shipping')) {
                obj['is_free_shipping'] = ApiClient.convertToType(data['is_free_shipping'], 'Boolean');
            }
            if (data.hasOwnProperty('taxable')) {
                obj['taxable'] = ApiClient.convertToType(data['taxable'], 'Boolean');
            }
            if (data.hasOwnProperty('seo_url')) {
                obj['seo_url'] = ApiClient.convertToType(data['seo_url'], 'String');
            }
            if (data.hasOwnProperty('manufacturer_id')) {
                obj['manufacturer_id'] = ApiClient.convertToType(data['manufacturer_id'], 'String');
            }
            if (data.hasOwnProperty('harmonized_system_code')) {
                obj['harmonized_system_code'] = ApiClient.convertToType(data['harmonized_system_code'], 'String');
            }
            if (data.hasOwnProperty('marketplace_item_properties')) {
                obj['marketplace_item_properties'] = ApiClient.convertToType(data['marketplace_item_properties'], Object);
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [ProductAddBatchPayloadInnerImagesInner]);
            }
            if (data.hasOwnProperty('product_images_ids')) {
                obj['product_images_ids'] = ApiClient.convertToType(data['product_images_ids'], ['String']);
            }
            if (data.hasOwnProperty('related_products_ids')) {
                obj['related_products_ids'] = ApiClient.convertToType(data['related_products_ids'], ['String']);
            }
            if (data.hasOwnProperty('up_sell_products_ids')) {
                obj['up_sell_products_ids'] = ApiClient.convertToType(data['up_sell_products_ids'], ['String']);
            }
            if (data.hasOwnProperty('cross_sell_products_ids')) {
                obj['cross_sell_products_ids'] = ApiClient.convertToType(data['cross_sell_products_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductVariantAddBatchPayloadInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductVariantAddBatchPayloadInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductVariantAddBatchPayloadInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['product_id'] && !(typeof data['product_id'] === 'string' || data['product_id'] instanceof String)) {
            throw new Error("Expected the field `product_id` to be a primitive type in the JSON string but got " + data['product_id']);
        }
        if (data['combination']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['combination'])) {
                throw new Error("Expected the field `combination` to be an array in the JSON data but got " + data['combination']);
            }
            // validate the optional field `combination` (array)
            for (const item of data['combination']) {
                ProductVariantAddBatchPayloadInnerCombinationInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['short_description'] && !(typeof data['short_description'] === 'string' || data['short_description'] instanceof String)) {
            throw new Error("Expected the field `short_description` to be a primitive type in the JSON string but got " + data['short_description']);
        }
        // ensure the json data is a string
        if (data['sku'] && !(typeof data['sku'] === 'string' || data['sku'] instanceof String)) {
            throw new Error("Expected the field `sku` to be a primitive type in the JSON string but got " + data['sku']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['sprice_create'] && !(typeof data['sprice_create'] === 'string' || data['sprice_create'] instanceof String)) {
            throw new Error("Expected the field `sprice_create` to be a primitive type in the JSON string but got " + data['sprice_create']);
        }
        // ensure the json data is a string
        if (data['sprice_expire'] && !(typeof data['sprice_expire'] === 'string' || data['sprice_expire'] instanceof String)) {
            throw new Error("Expected the field `sprice_expire` to be a primitive type in the JSON string but got " + data['sprice_expire']);
        }
        if (data['advanced_prices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['advanced_prices'])) {
                throw new Error("Expected the field `advanced_prices` to be an array in the JSON data but got " + data['advanced_prices']);
            }
            // validate the optional field `advanced_prices` (array)
            for (const item of data['advanced_prices']) {
                ProductUpdateBatchPayloadInnerAdvancedPricesInner.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['meta_keywords'])) {
            throw new Error("Expected the field `meta_keywords` to be an array in the JSON data but got " + data['meta_keywords']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['categories_ids'])) {
            throw new Error("Expected the field `categories_ids` to be an array in the JSON data but got " + data['categories_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['stores_ids'])) {
            throw new Error("Expected the field `stores_ids` to be an array in the JSON data but got " + data['stores_ids']);
        }
        // ensure the json data is a string
        if (data['weight_unit'] && !(typeof data['weight_unit'] === 'string' || data['weight_unit'] instanceof String)) {
            throw new Error("Expected the field `weight_unit` to be a primitive type in the JSON string but got " + data['weight_unit']);
        }
        // ensure the json data is a string
        if (data['warehouse_id'] && !(typeof data['warehouse_id'] === 'string' || data['warehouse_id'] instanceof String)) {
            throw new Error("Expected the field `warehouse_id` to be a primitive type in the JSON string but got " + data['warehouse_id']);
        }
        // ensure the json data is a string
        if (data['store_id'] && !(typeof data['store_id'] === 'string' || data['store_id'] instanceof String)) {
            throw new Error("Expected the field `store_id` to be a primitive type in the JSON string but got " + data['store_id']);
        }
        // ensure the json data is a string
        if (data['lang_id'] && !(typeof data['lang_id'] === 'string' || data['lang_id'] instanceof String)) {
            throw new Error("Expected the field `lang_id` to be a primitive type in the JSON string but got " + data['lang_id']);
        }
        // ensure the json data is a string
        if (data['tax_class_id'] && !(typeof data['tax_class_id'] === 'string' || data['tax_class_id'] instanceof String)) {
            throw new Error("Expected the field `tax_class_id` to be a primitive type in the JSON string but got " + data['tax_class_id']);
        }
        // ensure the json data is a string
        if (data['backorder_status'] && !(typeof data['backorder_status'] === 'string' || data['backorder_status'] instanceof String)) {
            throw new Error("Expected the field `backorder_status` to be a primitive type in the JSON string but got " + data['backorder_status']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['visible'] && !(typeof data['visible'] === 'string' || data['visible'] instanceof String)) {
            throw new Error("Expected the field `visible` to be a primitive type in the JSON string but got " + data['visible']);
        }
        // ensure the json data is a string
        if (data['upc'] && !(typeof data['upc'] === 'string' || data['upc'] instanceof String)) {
            throw new Error("Expected the field `upc` to be a primitive type in the JSON string but got " + data['upc']);
        }
        // ensure the json data is a string
        if (data['isbn'] && !(typeof data['isbn'] === 'string' || data['isbn'] instanceof String)) {
            throw new Error("Expected the field `isbn` to be a primitive type in the JSON string but got " + data['isbn']);
        }
        // ensure the json data is a string
        if (data['mpn'] && !(typeof data['mpn'] === 'string' || data['mpn'] instanceof String)) {
            throw new Error("Expected the field `mpn` to be a primitive type in the JSON string but got " + data['mpn']);
        }
        // ensure the json data is a string
        if (data['ean'] && !(typeof data['ean'] === 'string' || data['ean'] instanceof String)) {
            throw new Error("Expected the field `ean` to be a primitive type in the JSON string but got " + data['ean']);
        }
        // ensure the json data is a string
        if (data['barcode'] && !(typeof data['barcode'] === 'string' || data['barcode'] instanceof String)) {
            throw new Error("Expected the field `barcode` to be a primitive type in the JSON string but got " + data['barcode']);
        }
        // ensure the json data is a string
        if (data['seo_url'] && !(typeof data['seo_url'] === 'string' || data['seo_url'] instanceof String)) {
            throw new Error("Expected the field `seo_url` to be a primitive type in the JSON string but got " + data['seo_url']);
        }
        // ensure the json data is a string
        if (data['manufacturer_id'] && !(typeof data['manufacturer_id'] === 'string' || data['manufacturer_id'] instanceof String)) {
            throw new Error("Expected the field `manufacturer_id` to be a primitive type in the JSON string but got " + data['manufacturer_id']);
        }
        // ensure the json data is a string
        if (data['harmonized_system_code'] && !(typeof data['harmonized_system_code'] === 'string' || data['harmonized_system_code'] instanceof String)) {
            throw new Error("Expected the field `harmonized_system_code` to be a primitive type in the JSON string but got " + data['harmonized_system_code']);
        }
        if (data['images']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['images'])) {
                throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
            }
            // validate the optional field `images` (array)
            for (const item of data['images']) {
                ProductAddBatchPayloadInnerImagesInner.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['product_images_ids'])) {
            throw new Error("Expected the field `product_images_ids` to be an array in the JSON data but got " + data['product_images_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['related_products_ids'])) {
            throw new Error("Expected the field `related_products_ids` to be an array in the JSON data but got " + data['related_products_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['up_sell_products_ids'])) {
            throw new Error("Expected the field `up_sell_products_ids` to be an array in the JSON data but got " + data['up_sell_products_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['cross_sell_products_ids'])) {
            throw new Error("Expected the field `cross_sell_products_ids` to be an array in the JSON data but got " + data['cross_sell_products_ids']);
        }

        return true;
    }


}

ProductVariantAddBatchPayloadInner.RequiredProperties = ["product_id", "combination", "sku"];

/**
 * @member {String} product_id
 */
ProductVariantAddBatchPayloadInner.prototype['product_id'] = undefined;

/**
 * A unique combination that contains an array of options and their values, which form a variation.
 * @member {Array.<module:model/ProductVariantAddBatchPayloadInnerCombinationInner>} combination
 */
ProductVariantAddBatchPayloadInner.prototype['combination'] = undefined;

/**
 * @member {String} name
 */
ProductVariantAddBatchPayloadInner.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ProductVariantAddBatchPayloadInner.prototype['description'] = undefined;

/**
 * @member {String} short_description
 */
ProductVariantAddBatchPayloadInner.prototype['short_description'] = undefined;

/**
 * @member {String} sku
 */
ProductVariantAddBatchPayloadInner.prototype['sku'] = undefined;

/**
 * @member {String} model
 */
ProductVariantAddBatchPayloadInner.prototype['model'] = undefined;

/**
 * @member {Number} price
 */
ProductVariantAddBatchPayloadInner.prototype['price'] = undefined;

/**
 * @member {Number} old_price
 */
ProductVariantAddBatchPayloadInner.prototype['old_price'] = undefined;

/**
 * @member {Number} cost_price
 */
ProductVariantAddBatchPayloadInner.prototype['cost_price'] = undefined;

/**
 * @member {Number} special_price
 */
ProductVariantAddBatchPayloadInner.prototype['special_price'] = undefined;

/**
 * @member {String} sprice_create
 */
ProductVariantAddBatchPayloadInner.prototype['sprice_create'] = undefined;

/**
 * @member {String} sprice_expire
 */
ProductVariantAddBatchPayloadInner.prototype['sprice_expire'] = undefined;

/**
 * @member {Array.<module:model/ProductUpdateBatchPayloadInnerAdvancedPricesInner>} advanced_prices
 */
ProductVariantAddBatchPayloadInner.prototype['advanced_prices'] = undefined;

/**
 * @member {Number} meta_title
 */
ProductVariantAddBatchPayloadInner.prototype['meta_title'] = undefined;

/**
 * @member {Number} meta_description
 */
ProductVariantAddBatchPayloadInner.prototype['meta_description'] = undefined;

/**
 * @member {Array.<String>} meta_keywords
 */
ProductVariantAddBatchPayloadInner.prototype['meta_keywords'] = undefined;

/**
 * @member {Array.<String>} categories_ids
 */
ProductVariantAddBatchPayloadInner.prototype['categories_ids'] = undefined;

/**
 * @member {Array.<String>} stores_ids
 */
ProductVariantAddBatchPayloadInner.prototype['stores_ids'] = undefined;

/**
 * @member {Number} weight
 */
ProductVariantAddBatchPayloadInner.prototype['weight'] = undefined;

/**
 * @member {Number} width
 */
ProductVariantAddBatchPayloadInner.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
ProductVariantAddBatchPayloadInner.prototype['height'] = undefined;

/**
 * @member {Number} length
 */
ProductVariantAddBatchPayloadInner.prototype['length'] = undefined;

/**
 * @member {String} weight_unit
 */
ProductVariantAddBatchPayloadInner.prototype['weight_unit'] = undefined;

/**
 * @member {String} warehouse_id
 */
ProductVariantAddBatchPayloadInner.prototype['warehouse_id'] = undefined;

/**
 * @member {Number} quantity
 */
ProductVariantAddBatchPayloadInner.prototype['quantity'] = undefined;

/**
 * @member {Boolean} manage_stock
 */
ProductVariantAddBatchPayloadInner.prototype['manage_stock'] = undefined;

/**
 * @member {Boolean} in_stock
 */
ProductVariantAddBatchPayloadInner.prototype['in_stock'] = undefined;

/**
 * @member {String} store_id
 */
ProductVariantAddBatchPayloadInner.prototype['store_id'] = undefined;

/**
 * @member {String} lang_id
 */
ProductVariantAddBatchPayloadInner.prototype['lang_id'] = undefined;

/**
 * @member {String} tax_class_id
 */
ProductVariantAddBatchPayloadInner.prototype['tax_class_id'] = undefined;

/**
 * @member {String} backorder_status
 */
ProductVariantAddBatchPayloadInner.prototype['backorder_status'] = undefined;

/**
 * @member {String} status
 */
ProductVariantAddBatchPayloadInner.prototype['status'] = undefined;

/**
 * @member {String} visible
 */
ProductVariantAddBatchPayloadInner.prototype['visible'] = undefined;

/**
 * @member {Boolean} is_virtual
 */
ProductVariantAddBatchPayloadInner.prototype['is_virtual'] = undefined;

/**
 * @member {Boolean} downloadable
 */
ProductVariantAddBatchPayloadInner.prototype['downloadable'] = undefined;

/**
 * @member {Boolean} is_default
 */
ProductVariantAddBatchPayloadInner.prototype['is_default'] = undefined;

/**
 * @member {String} upc
 */
ProductVariantAddBatchPayloadInner.prototype['upc'] = undefined;

/**
 * @member {String} isbn
 */
ProductVariantAddBatchPayloadInner.prototype['isbn'] = undefined;

/**
 * @member {String} mpn
 */
ProductVariantAddBatchPayloadInner.prototype['mpn'] = undefined;

/**
 * @member {String} ean
 */
ProductVariantAddBatchPayloadInner.prototype['ean'] = undefined;

/**
 * @member {String} barcode
 */
ProductVariantAddBatchPayloadInner.prototype['barcode'] = undefined;

/**
 * @member {Boolean} available_for_sale
 */
ProductVariantAddBatchPayloadInner.prototype['available_for_sale'] = undefined;

/**
 * @member {Boolean} is_free_shipping
 */
ProductVariantAddBatchPayloadInner.prototype['is_free_shipping'] = undefined;

/**
 * @member {Boolean} taxable
 */
ProductVariantAddBatchPayloadInner.prototype['taxable'] = undefined;

/**
 * @member {String} seo_url
 */
ProductVariantAddBatchPayloadInner.prototype['seo_url'] = undefined;

/**
 * @member {String} manufacturer_id
 */
ProductVariantAddBatchPayloadInner.prototype['manufacturer_id'] = undefined;

/**
 * @member {String} harmonized_system_code
 */
ProductVariantAddBatchPayloadInner.prototype['harmonized_system_code'] = undefined;

/**
 * @member {Object} marketplace_item_properties
 */
ProductVariantAddBatchPayloadInner.prototype['marketplace_item_properties'] = undefined;

/**
 * @member {Array.<module:model/ProductAddBatchPayloadInnerImagesInner>} images
 */
ProductVariantAddBatchPayloadInner.prototype['images'] = undefined;

/**
 * @member {Array.<String>} product_images_ids
 */
ProductVariantAddBatchPayloadInner.prototype['product_images_ids'] = undefined;

/**
 * @member {Array.<String>} related_products_ids
 */
ProductVariantAddBatchPayloadInner.prototype['related_products_ids'] = undefined;

/**
 * @member {Array.<String>} up_sell_products_ids
 */
ProductVariantAddBatchPayloadInner.prototype['up_sell_products_ids'] = undefined;

/**
 * @member {Array.<String>} cross_sell_products_ids
 */
ProductVariantAddBatchPayloadInner.prototype['cross_sell_products_ids'] = undefined;






export default ProductVariantAddBatchPayloadInner;

