/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BatchJob from './BatchJob';

/**
 * The ResponseBatchJobListResult model module.
 * @module model/ResponseBatchJobListResult
 * @version 1.1
 */
class ResponseBatchJobListResult {
    /**
     * Constructs a new <code>ResponseBatchJobListResult</code>.
     * @alias module:model/ResponseBatchJobListResult
     */
    constructor() { 
        
        ResponseBatchJobListResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponseBatchJobListResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseBatchJobListResult} obj Optional instance to populate.
     * @return {module:model/ResponseBatchJobListResult} The populated <code>ResponseBatchJobListResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseBatchJobListResult();

            if (data.hasOwnProperty('jobs')) {
                obj['jobs'] = ApiClient.convertToType(data['jobs'], [BatchJob]);
            }
            if (data.hasOwnProperty('additional_fields')) {
                obj['additional_fields'] = ApiClient.convertToType(data['additional_fields'], Object);
            }
            if (data.hasOwnProperty('custom_fields')) {
                obj['custom_fields'] = ApiClient.convertToType(data['custom_fields'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseBatchJobListResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseBatchJobListResult</code>.
     */
    static validateJSON(data) {
        if (data['jobs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['jobs'])) {
                throw new Error("Expected the field `jobs` to be an array in the JSON data but got " + data['jobs']);
            }
            // validate the optional field `jobs` (array)
            for (const item of data['jobs']) {
                BatchJob.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/BatchJob>} jobs
 */
ResponseBatchJobListResult.prototype['jobs'] = undefined;

/**
 * @member {Object} additional_fields
 */
ResponseBatchJobListResult.prototype['additional_fields'] = undefined;

/**
 * @member {Object} custom_fields
 */
ResponseBatchJobListResult.prototype['custom_fields'] = undefined;






export default ResponseBatchJobListResult;

