/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api2CartOpenApi);
  }
}(this, function(expect, Api2CartOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api2CartOpenApi.OrderCalculate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderCalculate', function() {
    it('should create an instance of OrderCalculate', function() {
      // uncomment below and update the code to test OrderCalculate
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be.a(Api2CartOpenApi.OrderCalculate);
    });

    it('should have the property customerEmail (base name: "customer_email")', function() {
      // uncomment below and update the code to test the property customerEmail
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property currencyId (base name: "currency_id")', function() {
      // uncomment below and update the code to test the property currencyId
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property storeId (base name: "store_id")', function() {
      // uncomment below and update the code to test the property storeId
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property coupons (base name: "coupons")', function() {
      // uncomment below and update the code to test the property coupons
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippFirstName (base name: "shipp_first_name")', function() {
      // uncomment below and update the code to test the property shippFirstName
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippLastName (base name: "shipp_last_name")', function() {
      // uncomment below and update the code to test the property shippLastName
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippAddress1 (base name: "shipp_address_1")', function() {
      // uncomment below and update the code to test the property shippAddress1
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippAddress2 (base name: "shipp_address_2")', function() {
      // uncomment below and update the code to test the property shippAddress2
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippCity (base name: "shipp_city")', function() {
      // uncomment below and update the code to test the property shippCity
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippPostcode (base name: "shipp_postcode")', function() {
      // uncomment below and update the code to test the property shippPostcode
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippState (base name: "shipp_state")', function() {
      // uncomment below and update the code to test the property shippState
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippCountry (base name: "shipp_country")', function() {
      // uncomment below and update the code to test the property shippCountry
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippCompany (base name: "shipp_company")', function() {
      // uncomment below and update the code to test the property shippCompany
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property shippPhone (base name: "shipp_phone")', function() {
      // uncomment below and update the code to test the property shippPhone
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billFirstName (base name: "bill_first_name")', function() {
      // uncomment below and update the code to test the property billFirstName
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billLastName (base name: "bill_last_name")', function() {
      // uncomment below and update the code to test the property billLastName
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billAddress1 (base name: "bill_address_1")', function() {
      // uncomment below and update the code to test the property billAddress1
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billAddress2 (base name: "bill_address_2")', function() {
      // uncomment below and update the code to test the property billAddress2
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billCity (base name: "bill_city")', function() {
      // uncomment below and update the code to test the property billCity
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billPostcode (base name: "bill_postcode")', function() {
      // uncomment below and update the code to test the property billPostcode
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billState (base name: "bill_state")', function() {
      // uncomment below and update the code to test the property billState
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billCountry (base name: "bill_country")', function() {
      // uncomment below and update the code to test the property billCountry
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billCompany (base name: "bill_company")', function() {
      // uncomment below and update the code to test the property billCompany
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property billPhone (base name: "bill_phone")', function() {
      // uncomment below and update the code to test the property billPhone
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property responseFields (base name: "response_fields")', function() {
      // uncomment below and update the code to test the property responseFields
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

    it('should have the property orderItem (base name: "order_item")', function() {
      // uncomment below and update the code to test the property orderItem
      //var instance = new Api2CartOpenApi.OrderCalculate();
      //expect(instance).to.be();
    });

  });

}));
