/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api2CartOpenApi);
  }
}(this, function(expect, Api2CartOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api2CartOpenApi.ProductAddBestOffer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductAddBestOffer', function() {
    it('should create an instance of ProductAddBestOffer', function() {
      // uncomment below and update the code to test ProductAddBestOffer
      //var instance = new Api2CartOpenApi.ProductAddBestOffer();
      //expect(instance).to.be.a(Api2CartOpenApi.ProductAddBestOffer);
    });

    it('should have the property minimumOfferPrice (base name: "minimum_offer_price")', function() {
      // uncomment below and update the code to test the property minimumOfferPrice
      //var instance = new Api2CartOpenApi.ProductAddBestOffer();
      //expect(instance).to.be();
    });

    it('should have the property autoAcceptPrice (base name: "auto_accept_price")', function() {
      // uncomment below and update the code to test the property autoAcceptPrice
      //var instance = new Api2CartOpenApi.ProductAddBestOffer();
      //expect(instance).to.be();
    });

  });

}));
