/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api2CartOpenApi);
  }
}(this, function(expect, Api2CartOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api2CartOpenApi.ProductOptionAdd();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductOptionAdd', function() {
    it('should create an instance of ProductOptionAdd', function() {
      // uncomment below and update the code to test ProductOptionAdd
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be.a(Api2CartOpenApi.ProductOptionAdd);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "product_id")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property defaultOptionValue (base name: "default_option_value")', function() {
      // uncomment below and update the code to test the property defaultOptionValue
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property optionValues (base name: "option_values")', function() {
      // uncomment below and update the code to test the property optionValues
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property avail (base name: "avail")', function() {
      // uncomment below and update the code to test the property avail
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property sortOrder (base name: "sort_order")', function() {
      // uncomment below and update the code to test the property sortOrder
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property required (base name: "required")', function() {
      // uncomment below and update the code to test the property required
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property values (base name: "values")', function() {
      // uncomment below and update the code to test the property values
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

    it('should have the property clearCache (base name: "clear_cache")', function() {
      // uncomment below and update the code to test the property clearCache
      //var instance = new Api2CartOpenApi.ProductOptionAdd();
      //expect(instance).to.be();
    });

  });

}));
